
package cinemaswingtest1;

import java.util.ArrayList;
import java.util.List;

public class Global {
    public static String customer_email = "";
    public static String movie_name = "";
    public static String seat_no = "";
    public static String cnt_seat = "";
    public static String ticket_class = "";
    public static String fnb_price = "0";
    public static String day = "";
    public static String time = "";
    public static String Url=""; 
    public static int seat_movie1=78;
    public static int seat_movie2;
    public static int seat_movie3;
    public static int seat_movie4;
    public static int seat_movie5;
    public static int hall;
    public static int movie_idx;
    public static int remove_movie_idx;
    public static List<Integer> booked_seat0 = new ArrayList<>();
    public static List<Integer> booked_seat1 = new ArrayList<>();
    public static List<Integer> booked_seat2 = new ArrayList<>();
    public static List<Integer> booked_seat3 = new ArrayList<>();
    public static List<Integer> booked_seat4 = new ArrayList<>();
    public static List<Integer> booked_seat5 = new ArrayList<>();
    public static List<Integer> booked_seat6 = new ArrayList<>();
    public static List<Integer> booked_seat7 = new ArrayList<>();
    public static List<Integer> booked_seat8 = new ArrayList<>();
    public static List<Integer> booked_seat9 = new ArrayList<>();
    public static List<Integer> booked_seat10 = new ArrayList<>();
    public static List<Integer> booked_seat11 = new ArrayList<>();
    public static List<Integer> booked_seat12 = new ArrayList<>();
    public static List<Integer> booked_seat13 = new ArrayList<>();
    public static List<Integer> booked_seat14 = new ArrayList<>();
    public static List<Integer> booked_seat15 = new ArrayList<>();
    public static List<Integer> booked_seat16 = new ArrayList<>();
    public static List<Integer> booked_seat17 = new ArrayList<>();
    public static List<Integer> booked_seat18 = new ArrayList<>();
    public static List<Integer> booked_seat19 = new ArrayList<>();
    public static List<Integer> booked_seat20 = new ArrayList<>();
    public static List<Integer> booked_seat21 = new ArrayList<>();
    public static List<Integer> booked_seat22 = new ArrayList<>();
    public static List<Integer> booked_seat23 = new ArrayList<>();
    public static List<Integer> booked_seat24 = new ArrayList<>();
    public static List<Integer> booked_seat25 = new ArrayList<>();
    public static List<Integer> booked_seat26 = new ArrayList<>();
    public static List<Integer> booked_seat27 = new ArrayList<>();
    public static List<Integer> booked_seat28 = new ArrayList<>();
    public static List<Integer> booked_seat29 = new ArrayList<>();
    public static List<Integer> booked_seat30 = new ArrayList<>();
    public static List<Integer> booked_seat31 = new ArrayList<>();
    public static List<Integer> booked_seat32 = new ArrayList<>();
    public static List<Integer> booked_seat33 = new ArrayList<>();
    public static List<Integer> booked_seat34 = new ArrayList<>();
    public static List<Integer> booked_seat35 = new ArrayList<>();
    public static List<Integer> booked_seat36 = new ArrayList<>();
    public static List<Integer> booked_seat37 = new ArrayList<>();
    public static List<Integer> booked_seat38 = new ArrayList<>();
    public static List<Integer> booked_seat39 = new ArrayList<>();
    public static List<Integer> booked_seat40 = new ArrayList<>();
    public static List<Integer> booked_seat41 = new ArrayList<>();
    public static List<Integer> booked_seat42 = new ArrayList<>();
    public static List<Integer> booked_seat43 = new ArrayList<>();
    public static List<Integer> booked_seat44 = new ArrayList<>();
    
    
    public static List<List<Integer>> list = new ArrayList<>() {
        {
            add(booked_seat0);
            add(booked_seat1);
            add(booked_seat2);
            add(booked_seat3);
            add(booked_seat4);
            add(booked_seat5);
            add(booked_seat6);
            add(booked_seat7);
            add(booked_seat8);
            add(booked_seat9);
            add(booked_seat10);
            add(booked_seat11);
            add(booked_seat12);
            add(booked_seat13);
            add(booked_seat14);
            add(booked_seat15);
            add(booked_seat16);
            add(booked_seat17);
            add(booked_seat18);
            add(booked_seat19);
            add(booked_seat20);
            add(booked_seat21);
            add(booked_seat22);
            add(booked_seat23);
            add(booked_seat24);
            add(booked_seat25);
            add(booked_seat26);
            add(booked_seat27);
            add(booked_seat28);
            add(booked_seat29);
            add(booked_seat30);
            add(booked_seat31);
            add(booked_seat32);
            add(booked_seat33);
            add(booked_seat34);
            add(booked_seat35);
            add(booked_seat36);
            add(booked_seat37);
            add(booked_seat38);
            add(booked_seat39);
            add(booked_seat40);
            add(booked_seat41);
            add(booked_seat42);
            add(booked_seat43);
            add(booked_seat44);

        }
    };
    public static List<Integer> booked_seat0L = new ArrayList<>();
    public static List<Integer> booked_seat1L = new ArrayList<>();
    public static List<Integer> booked_seat2L = new ArrayList<>();
    public static List<Integer> booked_seat3L = new ArrayList<>();
    public static List<Integer> booked_seat4L = new ArrayList<>();
    public static List<Integer> booked_seat5L = new ArrayList<>();
    public static List<Integer> booked_seat6L = new ArrayList<>();
    public static List<Integer> booked_seat7L = new ArrayList<>();
    public static List<Integer> booked_seat8L = new ArrayList<>();
    public static List<Integer> booked_seat9L = new ArrayList<>();
    public static List<Integer> booked_seat10L = new ArrayList<>();
    public static List<Integer> booked_seat11L = new ArrayList<>();
    public static List<Integer> booked_seat12L = new ArrayList<>();
    public static List<Integer> booked_seat13L = new ArrayList<>();
    public static List<Integer> booked_seat14L = new ArrayList<>();
    public static List<Integer> booked_seat15L = new ArrayList<>();
    public static List<Integer> booked_seat16L = new ArrayList<>();
    public static List<Integer> booked_seat17L = new ArrayList<>();
    public static List<Integer> booked_seat18L = new ArrayList<>();
    public static List<Integer> booked_seat19L = new ArrayList<>();
    public static List<Integer> booked_seat20L = new ArrayList<>();
    public static List<Integer> booked_seat21L = new ArrayList<>();
    public static List<Integer> booked_seat22L = new ArrayList<>();
    public static List<Integer> booked_seat23L = new ArrayList<>();
    public static List<Integer> booked_seat24L = new ArrayList<>();
    public static List<Integer> booked_seat25L = new ArrayList<>();
    public static List<Integer> booked_seat26L = new ArrayList<>();
    public static List<Integer> booked_seat27L = new ArrayList<>();
    public static List<Integer> booked_seat28L = new ArrayList<>();
    public static List<Integer> booked_seat29L = new ArrayList<>();
    public static List<Integer> booked_seat30L = new ArrayList<>();
    public static List<Integer> booked_seat31L = new ArrayList<>();
    public static List<Integer> booked_seat32L = new ArrayList<>();
    public static List<Integer> booked_seat33L = new ArrayList<>();
    public static List<Integer> booked_seat34L = new ArrayList<>();
    public static List<Integer> booked_seat35L = new ArrayList<>();
    public static List<Integer> booked_seat36L = new ArrayList<>();
    public static List<Integer> booked_seat37L = new ArrayList<>();
    public static List<Integer> booked_seat38L = new ArrayList<>();
    public static List<Integer> booked_seat39L = new ArrayList<>();
    public static List<Integer> booked_seat40L = new ArrayList<>();
    public static List<Integer> booked_seat41L = new ArrayList<>();
    public static List<Integer> booked_seat42L = new ArrayList<>();
    public static List<Integer> booked_seat43L = new ArrayList<>();
    public static List<Integer> booked_seat44L = new ArrayList<>();
    
    public static List<List<Integer>> listL = new ArrayList<>() {
        {
            add(booked_seat0L);
            add(booked_seat1L);
            add(booked_seat2L);
            add(booked_seat3L);
            add(booked_seat4L);
            add(booked_seat5L);
            add(booked_seat6L);
            add(booked_seat7L);
            add(booked_seat8L);
            add(booked_seat9L);
            add(booked_seat10L);
            add(booked_seat11L);
            add(booked_seat12L);
            add(booked_seat13L);
            add(booked_seat14L);
            add(booked_seat15L);
            add(booked_seat16L);
            add(booked_seat17L);
            add(booked_seat18L);
            add(booked_seat19L);
            add(booked_seat20L);
            add(booked_seat21L);
            add(booked_seat22L);
            add(booked_seat23L);
            add(booked_seat24L);
            add(booked_seat25L);
            add(booked_seat26L);
            add(booked_seat27L);
            add(booked_seat28L);
            add(booked_seat29L);
            add(booked_seat30L);
            add(booked_seat31L);
            add(booked_seat32L);
            add(booked_seat33L);
            add(booked_seat34L);
            add(booked_seat35L);
            add(booked_seat36L);
            add(booked_seat37L);
            add(booked_seat38L);
            add(booked_seat39L);
            add(booked_seat40L);
            add(booked_seat41L);
            add(booked_seat42L);
            add(booked_seat43L);
            add(booked_seat44L);
        }
    };
    public static String ticket_student = "3";
    public static String ticket_classic;
    public static String ticket_premium;
}
