
package cinemaswingtest1;

import java.awt.Image;
import javax.swing.ImageIcon;

public class MainMenu extends javax.swing.JFrame {

    public MainMenu() {
        initComponents();
        ScaleImage();
        scaleImage();
        scaleImage1();
        scaleImage2();
        scaleImage3();
        scaleImage4();
        scaleImage5();
        scaleImage6();
        
    }
    
    public void ScaleImage(){
        ImageIcon icon = new ImageIcon("https://raw.githubusercontent.com/Christina-Ku-Pei-San/CinemaSwingTest1/main/CinemaSwingTest1/src/cinemaswingtest1/fop%20pic3.jpg");
        Image img=icon.getImage();        
        Image imgScale=img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon=new ImageIcon(imgScale);
        label.setIcon(scaledIcon);
    }
    
    public void scaleImage(){
    ImageIcon icon = new ImageIcon("C:\\Users\\YEZP\\Downloads\\WIX1001\\OIP.jpeg");
    Image img=icon.getImage();
    Image imgScale=img.getScaledInstance(label2.getWidth(), label2.getHeight(), Image.SCALE_SMOOTH);
    ImageIcon scaledIcon=new ImageIcon(imgScale);
    label2.setIcon(scaledIcon);
    }
    
    public void scaleImage1(){
    ImageIcon icon = new ImageIcon("C:\\Users\\YEZP\\Downloads\\WIX1001\\fop.jpg");
    Image img=icon.getImage();
    Image imgScale=img.getScaledInstance(label3.getWidth(), label3.getHeight(), Image.SCALE_SMOOTH);
    ImageIcon scaledIcon=new ImageIcon(imgScale);
    label3.setIcon(scaledIcon);
    }
    
    public void scaleImage2(){
    ImageIcon icon = new ImageIcon("C:\\Users\\YEZP\\Downloads\\WIX1001\\pic.jpg");
    Image img=icon.getImage();
    Image imgScale=img.getScaledInstance(label4.getWidth(), label4.getHeight(), Image.SCALE_SMOOTH);
    ImageIcon scaledIcon=new ImageIcon(imgScale);
    label4.setIcon(scaledIcon);
    }
    
    public void scaleImage3(){
    ImageIcon icon = new ImageIcon("C:\\Users\\YEZP\\Downloads\\WIX1001\\poster.jpg");
    Image img=icon.getImage();
    Image imgScale=img.getScaledInstance(label5.getWidth(), label5.getHeight(), Image.SCALE_SMOOTH);
    ImageIcon scaledIcon=new ImageIcon(imgScale);
    label5.setIcon(scaledIcon);
    }
    
    public void scaleImage4(){
    ImageIcon icon = new ImageIcon("C:\\Users\\YEZP\\Downloads\\WIX1001\\logo.png");
    Image img=icon.getImage();
    Image imgScale=img.getScaledInstance(label6.getWidth(), label6.getHeight(), Image.SCALE_SMOOTH);
    ImageIcon scaledIcon=new ImageIcon(imgScale);
    label6.setIcon(scaledIcon);
    }

    public void scaleImage5(){
    ImageIcon icon = new ImageIcon("C:\\Users\\YEZP\\Downloads\\WIX1001\\pic1.jpeg");
    Image img=icon.getImage();
    Image imgScale=img.getScaledInstance(label7.getWidth(), label7.getHeight(), Image.SCALE_SMOOTH);
    ImageIcon scaledIcon=new ImageIcon(imgScale);
    label7.setIcon(scaledIcon);
    }
    
    public void scaleImage6(){
    ImageIcon icon = new ImageIcon("C:\\Users\\YEZP\\Downloads\\WIX1001\\pic.jpeg");
    Image img=icon.getImage();
    Image imgScale=img.getScaledInstance(label8.getWidth(), label8.getHeight(), Image.SCALE_SMOOTH);
    ImageIcon scaledIcon=new ImageIcon(imgScale);
    label8.setIcon(scaledIcon);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label2 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        jLabel = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        label9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        label6 = new javax.swing.JLabel();
        label7 = new javax.swing.JLabel();
        label8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label2.setIcon(new javax.swing.ImageIcon("C:\\Users\\YEZP\\Downloads\\OIP.jpg")); // NOI18N

        label.setIcon(new javax.swing.ImageIcon("C:\\Users\\YEZP\\Downloads\\fop pic3.jpg")); // NOI18N

        label3.setIcon(new javax.swing.ImageIcon("C:\\Users\\YEZP\\Downloads\\fop.jpg")); // NOI18N

        jLabel.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 48)); // NOI18N
        jLabel.setForeground(new java.awt.Color(255, 255, 255));
        jLabel.setText("Now Showing");

        label4.setIcon(new javax.swing.ImageIcon("C:\\Users\\YEZP\\Downloads\\pic.jpg")); // NOI18N

        label5.setIcon(new javax.swing.ImageIcon("C:\\Users\\YEZP\\Downloads\\poster.jpg")); // NOI18N

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        jButton1.setText("Buy Now");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        label6.setIcon(new javax.swing.ImageIcon("C:\\Users\\YEZP\\Downloads\\logo.png")); // NOI18N

        label7.setIcon(new javax.swing.ImageIcon("C:\\Users\\YEZP\\Downloads\\pic1.jpg")); // NOI18N

        label8.setIcon(new javax.swing.ImageIcon("C:\\Users\\YEZP\\Downloads\\pic (1).jpg")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(label6)
                .addGap(240, 240, 240)
                .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(630, 630, 630)
                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(label5))
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(label))
            .addGroup(layout.createSequentialGroup()
                .addGap(440, 440, 440)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(470, 470, 470)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(label7)
            .addComponent(label8)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(label6))
                    .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label5)))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(label))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(400, 400, 400)
                .addComponent(jButton1))
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(label7))
            .addComponent(label8)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // after click Buy Now

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel label;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel label9;
    // End of variables declaration//GEN-END:variables
}
