package cinemaswingtest1;

import java.awt.Color;

public class Seat2 extends javax.swing.JFrame {

    private int a1,a2,a3,a4,a5,a6,
            b1,b2,b3,b4,b5,b6,
            c1,c2,c3,c4,c5,c6,
            d1,d2,d3,d4,d5,d6,
            e1,e2,e3,e4,e5,e6,
            f1,f2,f3,f4,f5,f6;

    /**
     * Creates new form Seat
     */
    public Seat2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnA01 = new javax.swing.JButton();
        btnA02 = new javax.swing.JButton();
        btnA05 = new javax.swing.JButton();
        btnA04 = new javax.swing.JButton();
        btnA08 = new javax.swing.JButton();
        btnA07 = new javax.swing.JButton();
        btnA11 = new javax.swing.JButton();
        btnA10 = new javax.swing.JButton();
        btnB01 = new javax.swing.JButton();
        btnB11 = new javax.swing.JButton();
        btnB03 = new javax.swing.JButton();
        btnB05 = new javax.swing.JButton();
        btnB07 = new javax.swing.JButton();
        btnB09 = new javax.swing.JButton();
        btnC10 = new javax.swing.JButton();
        btnC01 = new javax.swing.JButton();
        btnC02 = new javax.swing.JButton();
        btnD01 = new javax.swing.JButton();
        btnD11 = new javax.swing.JButton();
        btnC05 = new javax.swing.JButton();
        btnD03 = new javax.swing.JButton();
        btnD05 = new javax.swing.JButton();
        btnC04 = new javax.swing.JButton();
        btnD07 = new javax.swing.JButton();
        btnC08 = new javax.swing.JButton();
        btnD09 = new javax.swing.JButton();
        btnC07 = new javax.swing.JButton();
        btnC11 = new javax.swing.JButton();
        btnE10 = new javax.swing.JButton();
        btnE01 = new javax.swing.JButton();
        btnE02 = new javax.swing.JButton();
        btnF01 = new javax.swing.JButton();
        btnF11 = new javax.swing.JButton();
        btnE05 = new javax.swing.JButton();
        btnF03 = new javax.swing.JButton();
        btnF05 = new javax.swing.JButton();
        btnE04 = new javax.swing.JButton();
        btnF07 = new javax.swing.JButton();
        btnE08 = new javax.swing.JButton();
        btnF09 = new javax.swing.JButton();
        btnE07 = new javax.swing.JButton();
        btnE11 = new javax.swing.JButton();
        btnG10 = new javax.swing.JButton();
        btnG01 = new javax.swing.JButton();
        btnG02 = new javax.swing.JButton();
        btnH01 = new javax.swing.JButton();
        btnH11 = new javax.swing.JButton();
        btnG05 = new javax.swing.JButton();
        btnH03 = new javax.swing.JButton();
        btnH05 = new javax.swing.JButton();
        btnG04 = new javax.swing.JButton();
        btnH07 = new javax.swing.JButton();
        btnG08 = new javax.swing.JButton();
        btnH09 = new javax.swing.JButton();
        btnG07 = new javax.swing.JButton();
        btnG11 = new javax.swing.JButton();
        btnI10 = new javax.swing.JButton();
        btnI01 = new javax.swing.JButton();
        btnI02 = new javax.swing.JButton();
        btnJ01 = new javax.swing.JButton();
        btnJ11 = new javax.swing.JButton();
        btnI05 = new javax.swing.JButton();
        btnJ03 = new javax.swing.JButton();
        btnJ05 = new javax.swing.JButton();
        btnI04 = new javax.swing.JButton();
        btnJ07 = new javax.swing.JButton();
        btnI08 = new javax.swing.JButton();
        btnJ09 = new javax.swing.JButton();
        btnI07 = new javax.swing.JButton();
        btnI11 = new javax.swing.JButton();
        btnK10 = new javax.swing.JButton();
        btnK01 = new javax.swing.JButton();
        btnK02 = new javax.swing.JButton();
        btnK05 = new javax.swing.JButton();
        btnK04 = new javax.swing.JButton();
        btnK08 = new javax.swing.JButton();
        btnK07 = new javax.swing.JButton();
        btnK11 = new javax.swing.JButton();
        btnTwin1 = new javax.swing.JButton();
        btnTwin2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnAvailable = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnJ17 = new javax.swing.JButton();
        btnJ13 = new javax.swing.JButton();
        btnI14 = new javax.swing.JButton();
        btnJ15 = new javax.swing.JButton();
        btnI13 = new javax.swing.JButton();
        btnI17 = new javax.swing.JButton();
        btnK16 = new javax.swing.JButton();
        btnK14 = new javax.swing.JButton();
        btnK13 = new javax.swing.JButton();
        btnK17 = new javax.swing.JButton();
        btnA14 = new javax.swing.JButton();
        btnA13 = new javax.swing.JButton();
        btnA17 = new javax.swing.JButton();
        btnA16 = new javax.swing.JButton();
        btnB17 = new javax.swing.JButton();
        btnB13 = new javax.swing.JButton();
        btnB15 = new javax.swing.JButton();
        btnC16 = new javax.swing.JButton();
        btnD17 = new javax.swing.JButton();
        btnD13 = new javax.swing.JButton();
        btnC14 = new javax.swing.JButton();
        btnD15 = new javax.swing.JButton();
        btnC13 = new javax.swing.JButton();
        btnC17 = new javax.swing.JButton();
        btnE16 = new javax.swing.JButton();
        btnF17 = new javax.swing.JButton();
        btnF13 = new javax.swing.JButton();
        btnE14 = new javax.swing.JButton();
        btnF15 = new javax.swing.JButton();
        btnE13 = new javax.swing.JButton();
        btnE17 = new javax.swing.JButton();
        btnG16 = new javax.swing.JButton();
        btnH17 = new javax.swing.JButton();
        btnH13 = new javax.swing.JButton();
        btnG14 = new javax.swing.JButton();
        btnH15 = new javax.swing.JButton();
        btnG13 = new javax.swing.JButton();
        btnG17 = new javax.swing.JButton();
        btnI16 = new javax.swing.JButton();
        btnSelected = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnUnavailable = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1050, 640));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Seat");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 70, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("S C R E E N");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 57, 1031, -1));

        btnNext.setText("NEXT");
        getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 600, 60, 25));

        btnBack.setText("BACK");
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 602, -1, 25));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinemaswingtest1/image/mainmenu/logo (1).png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, -1));

        btnA01.setBackground(new java.awt.Color(255, 204, 255));
        btnA01.setText("A01");
        btnA01.setPreferredSize(new java.awt.Dimension(55, 25));
        btnA01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA01ActionPerformed(evt);
            }
        });
        getContentPane().add(btnA01, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        btnA02.setBackground(new java.awt.Color(255, 204, 255));
        btnA02.setText("A02");
        btnA02.setPreferredSize(new java.awt.Dimension(55, 25));
        btnA02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA02ActionPerformed(evt);
            }
        });
        getContentPane().add(btnA02, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 90, -1, -1));

        btnA05.setBackground(new java.awt.Color(255, 204, 255));
        btnA05.setText("A05");
        btnA05.setPreferredSize(new java.awt.Dimension(55, 25));
        btnA05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA05ActionPerformed(evt);
            }
        });
        getContentPane().add(btnA05, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 90, -1, -1));

        btnA04.setBackground(new java.awt.Color(255, 204, 255));
        btnA04.setText("A04");
        btnA04.setPreferredSize(new java.awt.Dimension(55, 25));
        btnA04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA04ActionPerformed(evt);
            }
        });
        getContentPane().add(btnA04, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 90, -1, -1));

        btnA08.setBackground(new java.awt.Color(255, 204, 255));
        btnA08.setText("A08");
        btnA08.setPreferredSize(new java.awt.Dimension(55, 25));
        btnA08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA08ActionPerformed(evt);
            }
        });
        getContentPane().add(btnA08, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 90, -1, -1));

        btnA07.setBackground(new java.awt.Color(255, 204, 255));
        btnA07.setText("A07");
        btnA07.setPreferredSize(new java.awt.Dimension(55, 25));
        btnA07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA07ActionPerformed(evt);
            }
        });
        getContentPane().add(btnA07, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 90, -1, -1));

        btnA11.setBackground(new java.awt.Color(255, 204, 255));
        btnA11.setText("A11");
        btnA11.setPreferredSize(new java.awt.Dimension(55, 25));
        btnA11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA11ActionPerformed(evt);
            }
        });
        getContentPane().add(btnA11, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, -1, -1));

        btnA10.setBackground(new java.awt.Color(255, 204, 255));
        btnA10.setText("A10");
        btnA10.setPreferredSize(new java.awt.Dimension(55, 25));
        btnA10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA10ActionPerformed(evt);
            }
        });
        getContentPane().add(btnA10, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 90, -1, -1));

        btnB01.setText("B01");
        btnB01.setPreferredSize(new java.awt.Dimension(55, 25));
        btnB01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnB01ActionPerformed(evt);
            }
        });
        getContentPane().add(btnB01, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 133, -1, -1));

        btnB11.setText("B11");
        btnB11.setPreferredSize(new java.awt.Dimension(55, 25));
        btnB11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnB11ActionPerformed(evt);
            }
        });
        getContentPane().add(btnB11, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 133, -1, -1));

        btnB03.setText("B03");
        btnB03.setPreferredSize(new java.awt.Dimension(55, 25));
        btnB03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnB03ActionPerformed(evt);
            }
        });
        getContentPane().add(btnB03, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 133, -1, -1));

        btnB05.setText("B05");
        btnB05.setPreferredSize(new java.awt.Dimension(55, 25));
        btnB05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnB05ActionPerformed(evt);
            }
        });
        getContentPane().add(btnB05, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 133, -1, -1));

        btnB07.setText("B07");
        btnB07.setPreferredSize(new java.awt.Dimension(55, 25));
        btnB07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnB07ActionPerformed(evt);
            }
        });
        getContentPane().add(btnB07, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 133, -1, -1));

        btnB09.setText("B09");
        btnB09.setPreferredSize(new java.awt.Dimension(55, 25));
        btnB09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnB09ActionPerformed(evt);
            }
        });
        getContentPane().add(btnB09, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 133, -1, -1));

        btnC10.setBackground(new java.awt.Color(255, 204, 255));
        btnC10.setText("C10");
        btnC10.setPreferredSize(new java.awt.Dimension(55, 25));
        btnC10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnC10ActionPerformed(evt);
            }
        });
        getContentPane().add(btnC10, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 176, -1, -1));

        btnC01.setBackground(new java.awt.Color(255, 204, 255));
        btnC01.setText("C01");
        btnC01.setPreferredSize(new java.awt.Dimension(55, 25));
        btnC01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnC01ActionPerformed(evt);
            }
        });
        getContentPane().add(btnC01, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 176, -1, -1));

        btnC02.setBackground(new java.awt.Color(255, 204, 255));
        btnC02.setText("C02");
        btnC02.setPreferredSize(new java.awt.Dimension(55, 25));
        btnC02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnC02ActionPerformed(evt);
            }
        });
        getContentPane().add(btnC02, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 176, -1, -1));

        btnD01.setText("D01");
        btnD01.setPreferredSize(new java.awt.Dimension(55, 25));
        btnD01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD01ActionPerformed(evt);
            }
        });
        getContentPane().add(btnD01, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 219, -1, -1));

        btnD11.setText("D11");
        btnD11.setPreferredSize(new java.awt.Dimension(55, 25));
        btnD11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD11ActionPerformed(evt);
            }
        });
        getContentPane().add(btnD11, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 219, -1, -1));

        btnC05.setBackground(new java.awt.Color(255, 204, 255));
        btnC05.setText("C05");
        btnC05.setPreferredSize(new java.awt.Dimension(55, 25));
        btnC05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnC05ActionPerformed(evt);
            }
        });
        getContentPane().add(btnC05, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 176, -1, -1));

        btnD03.setText("D03");
        btnD03.setPreferredSize(new java.awt.Dimension(55, 25));
        btnD03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD03ActionPerformed(evt);
            }
        });
        getContentPane().add(btnD03, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 219, -1, -1));

        btnD05.setText("D05");
        btnD05.setPreferredSize(new java.awt.Dimension(55, 25));
        btnD05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD05ActionPerformed(evt);
            }
        });
        getContentPane().add(btnD05, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 219, -1, -1));

        btnC04.setBackground(new java.awt.Color(255, 204, 255));
        btnC04.setText("C04");
        btnC04.setPreferredSize(new java.awt.Dimension(55, 25));
        btnC04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnC04ActionPerformed(evt);
            }
        });
        getContentPane().add(btnC04, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 176, -1, -1));

        btnD07.setText("D07");
        btnD07.setPreferredSize(new java.awt.Dimension(55, 25));
        btnD07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD07ActionPerformed(evt);
            }
        });
        getContentPane().add(btnD07, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 219, -1, -1));

        btnC08.setBackground(new java.awt.Color(255, 204, 255));
        btnC08.setText("C08");
        btnC08.setPreferredSize(new java.awt.Dimension(55, 25));
        btnC08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnC08ActionPerformed(evt);
            }
        });
        getContentPane().add(btnC08, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 176, -1, -1));

        btnD09.setText("D09");
        btnD09.setPreferredSize(new java.awt.Dimension(55, 25));
        btnD09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD09ActionPerformed(evt);
            }
        });
        getContentPane().add(btnD09, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 219, -1, -1));

        btnC07.setBackground(new java.awt.Color(255, 204, 255));
        btnC07.setText("C07");
        btnC07.setPreferredSize(new java.awt.Dimension(55, 25));
        btnC07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnC07ActionPerformed(evt);
            }
        });
        getContentPane().add(btnC07, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 176, -1, -1));

        btnC11.setBackground(new java.awt.Color(255, 204, 255));
        btnC11.setText("C11");
        btnC11.setPreferredSize(new java.awt.Dimension(55, 25));
        btnC11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnC11ActionPerformed(evt);
            }
        });
        getContentPane().add(btnC11, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 176, -1, -1));

        btnE10.setBackground(new java.awt.Color(255, 204, 255));
        btnE10.setText("E10");
        btnE10.setPreferredSize(new java.awt.Dimension(55, 25));
        btnE10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnE10ActionPerformed(evt);
            }
        });
        getContentPane().add(btnE10, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 262, -1, -1));

        btnE01.setBackground(new java.awt.Color(255, 204, 255));
        btnE01.setText("E01");
        btnE01.setPreferredSize(new java.awt.Dimension(55, 25));
        btnE01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnE01ActionPerformed(evt);
            }
        });
        getContentPane().add(btnE01, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 262, -1, -1));

        btnE02.setBackground(new java.awt.Color(255, 204, 255));
        btnE02.setText("E02");
        btnE02.setPreferredSize(new java.awt.Dimension(55, 25));
        btnE02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnE02ActionPerformed(evt);
            }
        });
        getContentPane().add(btnE02, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 262, -1, -1));

        btnF01.setText("F01");
        btnF01.setPreferredSize(new java.awt.Dimension(55, 25));
        btnF01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnF01ActionPerformed(evt);
            }
        });
        getContentPane().add(btnF01, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 305, -1, -1));

        btnF11.setText("F11");
        btnF11.setPreferredSize(new java.awt.Dimension(55, 25));
        btnF11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnF11ActionPerformed(evt);
            }
        });
        getContentPane().add(btnF11, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 305, -1, -1));

        btnE05.setBackground(new java.awt.Color(255, 204, 255));
        btnE05.setText("E05");
        btnE05.setPreferredSize(new java.awt.Dimension(55, 25));
        btnE05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnE05ActionPerformed(evt);
            }
        });
        getContentPane().add(btnE05, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 262, -1, -1));

        btnF03.setText("F03");
        btnF03.setPreferredSize(new java.awt.Dimension(55, 25));
        btnF03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnF03ActionPerformed(evt);
            }
        });
        getContentPane().add(btnF03, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 305, -1, -1));

        btnF05.setText("F05");
        btnF05.setPreferredSize(new java.awt.Dimension(55, 25));
        btnF05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnF05ActionPerformed(evt);
            }
        });
        getContentPane().add(btnF05, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 305, -1, -1));

        btnE04.setBackground(new java.awt.Color(255, 204, 255));
        btnE04.setText("E04");
        btnE04.setPreferredSize(new java.awt.Dimension(55, 25));
        btnE04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnE04ActionPerformed(evt);
            }
        });
        getContentPane().add(btnE04, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 262, -1, -1));

        btnF07.setText("F07");
        btnF07.setPreferredSize(new java.awt.Dimension(55, 25));
        btnF07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnF07ActionPerformed(evt);
            }
        });
        getContentPane().add(btnF07, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 305, -1, -1));

        btnE08.setBackground(new java.awt.Color(255, 204, 255));
        btnE08.setText("E08");
        btnE08.setPreferredSize(new java.awt.Dimension(55, 25));
        btnE08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnE08ActionPerformed(evt);
            }
        });
        getContentPane().add(btnE08, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 262, -1, -1));

        btnF09.setText("F09");
        btnF09.setPreferredSize(new java.awt.Dimension(55, 25));
        btnF09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnF09ActionPerformed(evt);
            }
        });
        getContentPane().add(btnF09, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 305, -1, -1));

        btnE07.setBackground(new java.awt.Color(255, 204, 255));
        btnE07.setText("E07");
        btnE07.setPreferredSize(new java.awt.Dimension(55, 25));
        btnE07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnE07ActionPerformed(evt);
            }
        });
        getContentPane().add(btnE07, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 262, -1, -1));

        btnE11.setBackground(new java.awt.Color(255, 204, 255));
        btnE11.setText("E11");
        btnE11.setPreferredSize(new java.awt.Dimension(55, 25));
        btnE11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnE11ActionPerformed(evt);
            }
        });
        getContentPane().add(btnE11, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 262, -1, -1));

        btnG10.setBackground(new java.awt.Color(255, 204, 255));
        btnG10.setText("G10");
        btnG10.setPreferredSize(new java.awt.Dimension(55, 25));
        btnG10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnG10ActionPerformed(evt);
            }
        });
        getContentPane().add(btnG10, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 348, -1, -1));

        btnG01.setBackground(new java.awt.Color(255, 204, 255));
        btnG01.setText("G01");
        btnG01.setPreferredSize(new java.awt.Dimension(55, 25));
        btnG01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnG01ActionPerformed(evt);
            }
        });
        getContentPane().add(btnG01, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 348, -1, -1));

        btnG02.setBackground(new java.awt.Color(255, 204, 255));
        btnG02.setText("G02");
        btnG02.setPreferredSize(new java.awt.Dimension(55, 25));
        btnG02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnG02ActionPerformed(evt);
            }
        });
        getContentPane().add(btnG02, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 348, -1, -1));

        btnH01.setText("H01");
        btnH01.setPreferredSize(new java.awt.Dimension(55, 25));
        btnH01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnH01ActionPerformed(evt);
            }
        });
        getContentPane().add(btnH01, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 391, -1, -1));

        btnH11.setText("H11");
        btnH11.setPreferredSize(new java.awt.Dimension(55, 25));
        btnH11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnH11ActionPerformed(evt);
            }
        });
        getContentPane().add(btnH11, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 391, -1, -1));

        btnG05.setBackground(new java.awt.Color(255, 204, 255));
        btnG05.setText("G05");
        btnG05.setPreferredSize(new java.awt.Dimension(55, 25));
        btnG05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnG05ActionPerformed(evt);
            }
        });
        getContentPane().add(btnG05, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 348, -1, -1));

        btnH03.setText("H03");
        btnH03.setPreferredSize(new java.awt.Dimension(55, 25));
        btnH03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnH03ActionPerformed(evt);
            }
        });
        getContentPane().add(btnH03, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 391, -1, -1));

        btnH05.setText("H05");
        btnH05.setPreferredSize(new java.awt.Dimension(55, 25));
        btnH05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnH05ActionPerformed(evt);
            }
        });
        getContentPane().add(btnH05, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 391, -1, -1));

        btnG04.setBackground(new java.awt.Color(255, 204, 255));
        btnG04.setText("G04");
        btnG04.setPreferredSize(new java.awt.Dimension(55, 25));
        btnG04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnG04ActionPerformed(evt);
            }
        });
        getContentPane().add(btnG04, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 348, -1, -1));

        btnH07.setText("H07");
        btnH07.setPreferredSize(new java.awt.Dimension(55, 25));
        btnH07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnH07ActionPerformed(evt);
            }
        });
        getContentPane().add(btnH07, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 391, -1, -1));

        btnG08.setBackground(new java.awt.Color(255, 204, 255));
        btnG08.setText("G08");
        btnG08.setPreferredSize(new java.awt.Dimension(55, 25));
        btnG08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnG08ActionPerformed(evt);
            }
        });
        getContentPane().add(btnG08, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 348, -1, -1));

        btnH09.setText("H09");
        btnH09.setPreferredSize(new java.awt.Dimension(55, 25));
        btnH09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnH09ActionPerformed(evt);
            }
        });
        getContentPane().add(btnH09, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 391, -1, -1));

        btnG07.setBackground(new java.awt.Color(255, 204, 255));
        btnG07.setText("G07");
        btnG07.setPreferredSize(new java.awt.Dimension(55, 25));
        btnG07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnG07ActionPerformed(evt);
            }
        });
        getContentPane().add(btnG07, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 348, -1, -1));

        btnG11.setBackground(new java.awt.Color(255, 204, 255));
        btnG11.setText("G11");
        btnG11.setPreferredSize(new java.awt.Dimension(55, 25));
        btnG11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnG11ActionPerformed(evt);
            }
        });
        getContentPane().add(btnG11, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 348, -1, -1));

        btnI10.setBackground(new java.awt.Color(255, 204, 255));
        btnI10.setText("I10");
        btnI10.setPreferredSize(new java.awt.Dimension(55, 25));
        btnI10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnI10ActionPerformed(evt);
            }
        });
        getContentPane().add(btnI10, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 434, -1, -1));

        btnI01.setBackground(new java.awt.Color(255, 204, 255));
        btnI01.setText("I01");
        btnI01.setPreferredSize(new java.awt.Dimension(55, 25));
        btnI01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnI01ActionPerformed(evt);
            }
        });
        getContentPane().add(btnI01, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 434, -1, -1));

        btnI02.setBackground(new java.awt.Color(255, 204, 255));
        btnI02.setText("I02");
        btnI02.setPreferredSize(new java.awt.Dimension(55, 25));
        btnI02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnI02ActionPerformed(evt);
            }
        });
        getContentPane().add(btnI02, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 434, -1, -1));

        btnJ01.setText("J01");
        btnJ01.setPreferredSize(new java.awt.Dimension(55, 25));
        btnJ01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJ01ActionPerformed(evt);
            }
        });
        getContentPane().add(btnJ01, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 477, -1, -1));

        btnJ11.setText("J11");
        btnJ11.setPreferredSize(new java.awt.Dimension(55, 25));
        btnJ11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJ11ActionPerformed(evt);
            }
        });
        getContentPane().add(btnJ11, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 477, -1, -1));

        btnI05.setBackground(new java.awt.Color(255, 204, 255));
        btnI05.setText("I05");
        btnI05.setPreferredSize(new java.awt.Dimension(55, 25));
        btnI05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnI05ActionPerformed(evt);
            }
        });
        getContentPane().add(btnI05, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 434, -1, -1));

        btnJ03.setText("J03");
        btnJ03.setPreferredSize(new java.awt.Dimension(55, 25));
        btnJ03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJ03ActionPerformed(evt);
            }
        });
        getContentPane().add(btnJ03, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 477, -1, -1));

        btnJ05.setText("J05");
        btnJ05.setPreferredSize(new java.awt.Dimension(55, 25));
        btnJ05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJ05ActionPerformed(evt);
            }
        });
        getContentPane().add(btnJ05, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 477, -1, -1));

        btnI04.setBackground(new java.awt.Color(255, 204, 255));
        btnI04.setText("I04");
        btnI04.setPreferredSize(new java.awt.Dimension(55, 25));
        btnI04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnI04ActionPerformed(evt);
            }
        });
        getContentPane().add(btnI04, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 434, -1, -1));

        btnJ07.setText("J07");
        btnJ07.setPreferredSize(new java.awt.Dimension(55, 25));
        btnJ07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJ07ActionPerformed(evt);
            }
        });
        getContentPane().add(btnJ07, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 477, -1, -1));

        btnI08.setBackground(new java.awt.Color(255, 204, 255));
        btnI08.setText("I08");
        btnI08.setPreferredSize(new java.awt.Dimension(55, 25));
        btnI08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnI08ActionPerformed(evt);
            }
        });
        getContentPane().add(btnI08, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 434, -1, -1));

        btnJ09.setText("J09");
        btnJ09.setPreferredSize(new java.awt.Dimension(55, 25));
        btnJ09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJ09ActionPerformed(evt);
            }
        });
        getContentPane().add(btnJ09, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 477, -1, -1));

        btnI07.setBackground(new java.awt.Color(255, 204, 255));
        btnI07.setText("I07");
        btnI07.setPreferredSize(new java.awt.Dimension(55, 25));
        btnI07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnI07ActionPerformed(evt);
            }
        });
        getContentPane().add(btnI07, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 434, -1, -1));

        btnI11.setBackground(new java.awt.Color(255, 204, 255));
        btnI11.setText("I11");
        btnI11.setPreferredSize(new java.awt.Dimension(55, 25));
        btnI11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnI11ActionPerformed(evt);
            }
        });
        getContentPane().add(btnI11, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 434, -1, -1));

        btnK10.setBackground(new java.awt.Color(255, 204, 255));
        btnK10.setText("K10");
        btnK10.setPreferredSize(new java.awt.Dimension(55, 25));
        btnK10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK10ActionPerformed(evt);
            }
        });
        getContentPane().add(btnK10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 520, -1, -1));

        btnK01.setBackground(new java.awt.Color(255, 204, 255));
        btnK01.setText("K01");
        btnK01.setPreferredSize(new java.awt.Dimension(55, 25));
        btnK01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK01ActionPerformed(evt);
            }
        });
        getContentPane().add(btnK01, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, -1));

        btnK02.setBackground(new java.awt.Color(255, 204, 255));
        btnK02.setText("K02");
        btnK02.setPreferredSize(new java.awt.Dimension(55, 25));
        btnK02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK02ActionPerformed(evt);
            }
        });
        getContentPane().add(btnK02, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 520, -1, -1));

        btnK05.setBackground(new java.awt.Color(255, 204, 255));
        btnK05.setText("K05");
        btnK05.setPreferredSize(new java.awt.Dimension(55, 25));
        btnK05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK05ActionPerformed(evt);
            }
        });
        getContentPane().add(btnK05, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 520, -1, -1));

        btnK04.setBackground(new java.awt.Color(255, 204, 255));
        btnK04.setText("K04");
        btnK04.setPreferredSize(new java.awt.Dimension(55, 25));
        btnK04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK04ActionPerformed(evt);
            }
        });
        getContentPane().add(btnK04, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 520, -1, -1));

        btnK08.setBackground(new java.awt.Color(255, 204, 255));
        btnK08.setText("K08");
        btnK08.setPreferredSize(new java.awt.Dimension(55, 25));
        btnK08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK08ActionPerformed(evt);
            }
        });
        getContentPane().add(btnK08, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 520, -1, -1));

        btnK07.setBackground(new java.awt.Color(255, 204, 255));
        btnK07.setText("K07");
        btnK07.setPreferredSize(new java.awt.Dimension(55, 25));
        btnK07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK07ActionPerformed(evt);
            }
        });
        getContentPane().add(btnK07, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 520, -1, -1));

        btnK11.setBackground(new java.awt.Color(255, 204, 255));
        btnK11.setText("K11");
        btnK11.setPreferredSize(new java.awt.Dimension(55, 25));
        btnK11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK11ActionPerformed(evt);
            }
        });
        getContentPane().add(btnK11, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 520, -1, -1));

        btnTwin1.setBackground(new java.awt.Color(255, 204, 255));
        btnTwin1.setPreferredSize(new java.awt.Dimension(55, 25));
        getContentPane().add(btnTwin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 602, -1, -1));

        btnTwin2.setBackground(new java.awt.Color(255, 204, 255));
        btnTwin2.setPreferredSize(new java.awt.Dimension(55, 25));
        getContentPane().add(btnTwin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 602, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Twin");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 602, -1, 25));

        btnAvailable.setPreferredSize(new java.awt.Dimension(55, 25));
        getContentPane().add(btnAvailable, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 602, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Available");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 602, 50, 25));

        btnJ17.setText("J17");
        btnJ17.setPreferredSize(new java.awt.Dimension(55, 25));
        btnJ17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJ17ActionPerformed(evt);
            }
        });
        getContentPane().add(btnJ17, new org.netbeans.lib.awtextra.AbsoluteConstraints(986, 477, -1, -1));

        btnJ13.setText("J13");
        btnJ13.setPreferredSize(new java.awt.Dimension(55, 25));
        btnJ13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJ13ActionPerformed(evt);
            }
        });
        getContentPane().add(btnJ13, new org.netbeans.lib.awtextra.AbsoluteConstraints(742, 477, -1, -1));

        btnI14.setBackground(new java.awt.Color(255, 204, 255));
        btnI14.setText("I14");
        btnI14.setPreferredSize(new java.awt.Dimension(55, 25));
        btnI14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnI14ActionPerformed(evt);
            }
        });
        getContentPane().add(btnI14, new org.netbeans.lib.awtextra.AbsoluteConstraints(803, 434, -1, -1));

        btnJ15.setText("J15");
        btnJ15.setPreferredSize(new java.awt.Dimension(55, 25));
        btnJ15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJ15ActionPerformed(evt);
            }
        });
        getContentPane().add(btnJ15, new org.netbeans.lib.awtextra.AbsoluteConstraints(864, 477, -1, -1));

        btnI13.setBackground(new java.awt.Color(255, 204, 255));
        btnI13.setText("I13");
        btnI13.setPreferredSize(new java.awt.Dimension(55, 25));
        btnI13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnI13ActionPerformed(evt);
            }
        });
        getContentPane().add(btnI13, new org.netbeans.lib.awtextra.AbsoluteConstraints(742, 434, -1, -1));

        btnI17.setBackground(new java.awt.Color(255, 204, 255));
        btnI17.setText("I17");
        btnI17.setPreferredSize(new java.awt.Dimension(55, 25));
        btnI17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnI17ActionPerformed(evt);
            }
        });
        getContentPane().add(btnI17, new org.netbeans.lib.awtextra.AbsoluteConstraints(986, 434, -1, -1));

        btnK16.setBackground(new java.awt.Color(255, 204, 255));
        btnK16.setText("K16");
        btnK16.setPreferredSize(new java.awt.Dimension(55, 25));
        btnK16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK16ActionPerformed(evt);
            }
        });
        getContentPane().add(btnK16, new org.netbeans.lib.awtextra.AbsoluteConstraints(925, 520, -1, -1));

        btnK14.setBackground(new java.awt.Color(255, 204, 255));
        btnK14.setText("K14");
        btnK14.setPreferredSize(new java.awt.Dimension(55, 25));
        btnK14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK14ActionPerformed(evt);
            }
        });
        getContentPane().add(btnK14, new org.netbeans.lib.awtextra.AbsoluteConstraints(803, 520, -1, -1));

        btnK13.setBackground(new java.awt.Color(255, 204, 255));
        btnK13.setText("K13");
        btnK13.setPreferredSize(new java.awt.Dimension(55, 25));
        btnK13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK13ActionPerformed(evt);
            }
        });
        getContentPane().add(btnK13, new org.netbeans.lib.awtextra.AbsoluteConstraints(742, 520, -1, -1));

        btnK17.setBackground(new java.awt.Color(255, 204, 255));
        btnK17.setText("K17");
        btnK17.setPreferredSize(new java.awt.Dimension(55, 25));
        btnK17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK17ActionPerformed(evt);
            }
        });
        getContentPane().add(btnK17, new org.netbeans.lib.awtextra.AbsoluteConstraints(986, 520, -1, -1));

        btnA14.setBackground(new java.awt.Color(255, 204, 255));
        btnA14.setText("A14");
        btnA14.setPreferredSize(new java.awt.Dimension(55, 25));
        btnA14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA14ActionPerformed(evt);
            }
        });
        getContentPane().add(btnA14, new org.netbeans.lib.awtextra.AbsoluteConstraints(803, 90, -1, -1));

        btnA13.setBackground(new java.awt.Color(255, 204, 255));
        btnA13.setText("A13");
        btnA13.setPreferredSize(new java.awt.Dimension(55, 25));
        btnA13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA13ActionPerformed(evt);
            }
        });
        getContentPane().add(btnA13, new org.netbeans.lib.awtextra.AbsoluteConstraints(742, 90, -1, -1));

        btnA17.setBackground(new java.awt.Color(255, 204, 255));
        btnA17.setText("A17");
        btnA17.setPreferredSize(new java.awt.Dimension(55, 25));
        btnA17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA17ActionPerformed(evt);
            }
        });
        getContentPane().add(btnA17, new org.netbeans.lib.awtextra.AbsoluteConstraints(986, 90, -1, -1));

        btnA16.setBackground(new java.awt.Color(255, 204, 255));
        btnA16.setText("A16");
        btnA16.setPreferredSize(new java.awt.Dimension(55, 25));
        btnA16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA16ActionPerformed(evt);
            }
        });
        getContentPane().add(btnA16, new org.netbeans.lib.awtextra.AbsoluteConstraints(925, 90, -1, -1));

        btnB17.setText("B17");
        btnB17.setPreferredSize(new java.awt.Dimension(55, 25));
        btnB17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnB17ActionPerformed(evt);
            }
        });
        getContentPane().add(btnB17, new org.netbeans.lib.awtextra.AbsoluteConstraints(986, 133, -1, -1));

        btnB13.setText("B13");
        btnB13.setPreferredSize(new java.awt.Dimension(55, 25));
        btnB13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnB13ActionPerformed(evt);
            }
        });
        getContentPane().add(btnB13, new org.netbeans.lib.awtextra.AbsoluteConstraints(742, 133, -1, -1));

        btnB15.setText("B15");
        btnB15.setPreferredSize(new java.awt.Dimension(55, 25));
        btnB15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnB15ActionPerformed(evt);
            }
        });
        getContentPane().add(btnB15, new org.netbeans.lib.awtextra.AbsoluteConstraints(864, 133, -1, -1));

        btnC16.setBackground(new java.awt.Color(255, 204, 255));
        btnC16.setText("C16");
        btnC16.setPreferredSize(new java.awt.Dimension(55, 25));
        btnC16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnC16ActionPerformed(evt);
            }
        });
        getContentPane().add(btnC16, new org.netbeans.lib.awtextra.AbsoluteConstraints(925, 176, -1, -1));

        btnD17.setText("D17");
        btnD17.setPreferredSize(new java.awt.Dimension(55, 25));
        btnD17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD17ActionPerformed(evt);
            }
        });
        getContentPane().add(btnD17, new org.netbeans.lib.awtextra.AbsoluteConstraints(986, 219, -1, -1));

        btnD13.setText("D13");
        btnD13.setPreferredSize(new java.awt.Dimension(55, 25));
        btnD13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD13ActionPerformed(evt);
            }
        });
        getContentPane().add(btnD13, new org.netbeans.lib.awtextra.AbsoluteConstraints(742, 219, -1, -1));

        btnC14.setBackground(new java.awt.Color(255, 204, 255));
        btnC14.setText("C14");
        btnC14.setPreferredSize(new java.awt.Dimension(55, 25));
        btnC14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnC14ActionPerformed(evt);
            }
        });
        getContentPane().add(btnC14, new org.netbeans.lib.awtextra.AbsoluteConstraints(803, 176, -1, -1));

        btnD15.setText("D15");
        btnD15.setPreferredSize(new java.awt.Dimension(55, 25));
        btnD15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD15ActionPerformed(evt);
            }
        });
        getContentPane().add(btnD15, new org.netbeans.lib.awtextra.AbsoluteConstraints(864, 219, -1, -1));

        btnC13.setBackground(new java.awt.Color(255, 204, 255));
        btnC13.setText("C13");
        btnC13.setPreferredSize(new java.awt.Dimension(55, 25));
        btnC13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnC13ActionPerformed(evt);
            }
        });
        getContentPane().add(btnC13, new org.netbeans.lib.awtextra.AbsoluteConstraints(742, 176, -1, -1));

        btnC17.setBackground(new java.awt.Color(255, 204, 255));
        btnC17.setText("C17");
        btnC17.setPreferredSize(new java.awt.Dimension(55, 25));
        btnC17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnC17ActionPerformed(evt);
            }
        });
        getContentPane().add(btnC17, new org.netbeans.lib.awtextra.AbsoluteConstraints(986, 176, -1, -1));

        btnE16.setBackground(new java.awt.Color(255, 204, 255));
        btnE16.setText("E16");
        btnE16.setPreferredSize(new java.awt.Dimension(55, 25));
        btnE16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnE16ActionPerformed(evt);
            }
        });
        getContentPane().add(btnE16, new org.netbeans.lib.awtextra.AbsoluteConstraints(925, 262, -1, -1));

        btnF17.setText("F17");
        btnF17.setPreferredSize(new java.awt.Dimension(55, 25));
        btnF17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnF17ActionPerformed(evt);
            }
        });
        getContentPane().add(btnF17, new org.netbeans.lib.awtextra.AbsoluteConstraints(986, 305, -1, -1));

        btnF13.setText("F13");
        btnF13.setPreferredSize(new java.awt.Dimension(55, 25));
        btnF13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnF13ActionPerformed(evt);
            }
        });
        getContentPane().add(btnF13, new org.netbeans.lib.awtextra.AbsoluteConstraints(742, 305, -1, -1));

        btnE14.setBackground(new java.awt.Color(255, 204, 255));
        btnE14.setText("E14");
        btnE14.setPreferredSize(new java.awt.Dimension(55, 25));
        btnE14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnE14ActionPerformed(evt);
            }
        });
        getContentPane().add(btnE14, new org.netbeans.lib.awtextra.AbsoluteConstraints(803, 262, -1, -1));

        btnF15.setText("F15");
        btnF15.setPreferredSize(new java.awt.Dimension(55, 25));
        btnF15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnF15ActionPerformed(evt);
            }
        });
        getContentPane().add(btnF15, new org.netbeans.lib.awtextra.AbsoluteConstraints(864, 305, -1, -1));

        btnE13.setBackground(new java.awt.Color(255, 204, 255));
        btnE13.setText("E13");
        btnE13.setPreferredSize(new java.awt.Dimension(55, 25));
        btnE13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnE13ActionPerformed(evt);
            }
        });
        getContentPane().add(btnE13, new org.netbeans.lib.awtextra.AbsoluteConstraints(742, 262, -1, -1));

        btnE17.setBackground(new java.awt.Color(255, 204, 255));
        btnE17.setText("E17");
        btnE17.setPreferredSize(new java.awt.Dimension(55, 25));
        btnE17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnE17ActionPerformed(evt);
            }
        });
        getContentPane().add(btnE17, new org.netbeans.lib.awtextra.AbsoluteConstraints(986, 262, -1, -1));

        btnG16.setBackground(new java.awt.Color(255, 204, 255));
        btnG16.setText("G16");
        btnG16.setPreferredSize(new java.awt.Dimension(55, 25));
        btnG16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnG16ActionPerformed(evt);
            }
        });
        getContentPane().add(btnG16, new org.netbeans.lib.awtextra.AbsoluteConstraints(925, 348, -1, -1));

        btnH17.setText("H17");
        btnH17.setPreferredSize(new java.awt.Dimension(55, 25));
        btnH17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnH17ActionPerformed(evt);
            }
        });
        getContentPane().add(btnH17, new org.netbeans.lib.awtextra.AbsoluteConstraints(986, 391, -1, -1));

        btnH13.setText("H13");
        btnH13.setPreferredSize(new java.awt.Dimension(55, 25));
        btnH13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnH13ActionPerformed(evt);
            }
        });
        getContentPane().add(btnH13, new org.netbeans.lib.awtextra.AbsoluteConstraints(742, 391, -1, -1));

        btnG14.setBackground(new java.awt.Color(255, 204, 255));
        btnG14.setText("G14");
        btnG14.setPreferredSize(new java.awt.Dimension(55, 25));
        btnG14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnG14ActionPerformed(evt);
            }
        });
        getContentPane().add(btnG14, new org.netbeans.lib.awtextra.AbsoluteConstraints(803, 348, -1, -1));

        btnH15.setText("H15");
        btnH15.setPreferredSize(new java.awt.Dimension(55, 25));
        btnH15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnH15ActionPerformed(evt);
            }
        });
        getContentPane().add(btnH15, new org.netbeans.lib.awtextra.AbsoluteConstraints(864, 391, -1, -1));

        btnG13.setBackground(new java.awt.Color(255, 204, 255));
        btnG13.setText("G13");
        btnG13.setPreferredSize(new java.awt.Dimension(55, 25));
        btnG13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnG13ActionPerformed(evt);
            }
        });
        getContentPane().add(btnG13, new org.netbeans.lib.awtextra.AbsoluteConstraints(742, 348, -1, -1));

        btnG17.setBackground(new java.awt.Color(255, 204, 255));
        btnG17.setText("G17");
        btnG17.setPreferredSize(new java.awt.Dimension(55, 25));
        btnG17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnG17ActionPerformed(evt);
            }
        });
        getContentPane().add(btnG17, new org.netbeans.lib.awtextra.AbsoluteConstraints(986, 348, -1, -1));

        btnI16.setBackground(new java.awt.Color(255, 204, 255));
        btnI16.setText("I16");
        btnI16.setPreferredSize(new java.awt.Dimension(55, 25));
        btnI16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnI16ActionPerformed(evt);
            }
        });
        getContentPane().add(btnI16, new org.netbeans.lib.awtextra.AbsoluteConstraints(925, 434, -1, -1));

        btnSelected.setBackground(new java.awt.Color(255, 255, 0));
        btnSelected.setPreferredSize(new java.awt.Dimension(55, 25));
        getContentPane().add(btnSelected, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 602, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Selected");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 600, 50, 30));

        btnUnavailable.setBackground(new java.awt.Color(102, 102, 102));
        btnUnavailable.setPreferredSize(new java.awt.Dimension(55, 25));
        getContentPane().add(btnUnavailable, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 600, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Unavailable");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 600, 60, 25));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinemaswingtest1/image/mainmenu/dark grey (2).jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnA01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnA01ActionPerformed

    private void btnA02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnA02ActionPerformed

    private void btnA04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnA04ActionPerformed

    private void btnA05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA05ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnA05ActionPerformed

    private void btnA07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA07ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnA07ActionPerformed

    private void btnA08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA08ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnA08ActionPerformed

    private void btnA10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnA10ActionPerformed

    private void btnA11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnA11ActionPerformed

    private void btnA13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnA13ActionPerformed

    private void btnA14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnA14ActionPerformed

    private void btnA16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnA16ActionPerformed

    private void btnA17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnA17ActionPerformed

    private void btnB01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnB01ActionPerformed

    private void btnB03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB03ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnB03ActionPerformed

    private void btnB05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB05ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnB05ActionPerformed

    private void btnB07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB07ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnB07ActionPerformed

    private void btnB09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB09ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnB09ActionPerformed

    private void btnB11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnB11ActionPerformed

    private void btnB13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnB13ActionPerformed

    private void btnB15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnB15ActionPerformed

    private void btnB17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnB17ActionPerformed

    private void btnC01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnC01ActionPerformed

    private void btnC02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnC02ActionPerformed

    private void btnC04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnC04ActionPerformed

    private void btnC05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC05ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnC05ActionPerformed

    private void btnC07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC07ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnC07ActionPerformed

    private void btnC08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC08ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnC08ActionPerformed

    private void btnC10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnC10ActionPerformed

    private void btnC11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnC11ActionPerformed

    private void btnC13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnC13ActionPerformed

    private void btnC14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnC14ActionPerformed

    private void btnC16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnC16ActionPerformed

    private void btnC17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnC17ActionPerformed

    private void btnD01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnD01ActionPerformed

    private void btnD03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD03ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnD03ActionPerformed

    private void btnD05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD05ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnD05ActionPerformed

    private void btnD07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD07ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnD07ActionPerformed

    private void btnD09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD09ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnD09ActionPerformed

    private void btnD11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnD11ActionPerformed

    private void btnD13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnD13ActionPerformed

    private void btnD15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnD15ActionPerformed

    private void btnD17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnD17ActionPerformed

    private void btnE01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnE01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnE01ActionPerformed

    private void btnE02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnE02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnE02ActionPerformed

    private void btnE04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnE04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnE04ActionPerformed

    private void btnE05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnE05ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnE05ActionPerformed

    private void btnE07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnE07ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnE07ActionPerformed

    private void btnE08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnE08ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnE08ActionPerformed

    private void btnE10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnE10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnE10ActionPerformed

    private void btnE11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnE11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnE11ActionPerformed

    private void btnE13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnE13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnE13ActionPerformed

    private void btnE14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnE14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnE14ActionPerformed

    private void btnE16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnE16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnE16ActionPerformed

    private void btnE17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnE17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnE17ActionPerformed

    private void btnF01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnF01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnF01ActionPerformed

    private void btnF03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnF03ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnF03ActionPerformed

    private void btnF05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnF05ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnF05ActionPerformed

    private void btnF07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnF07ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnF07ActionPerformed

    private void btnF09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnF09ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnF09ActionPerformed

    private void btnF11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnF11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnF11ActionPerformed

    private void btnF13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnF13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnF13ActionPerformed

    private void btnF15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnF15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnF15ActionPerformed

    private void btnF17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnF17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnF17ActionPerformed

    private void btnG01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnG01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnG01ActionPerformed

    private void btnG02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnG02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnG02ActionPerformed

    private void btnG04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnG04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnG04ActionPerformed

    private void btnG05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnG05ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnG05ActionPerformed

    private void btnG07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnG07ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnG07ActionPerformed

    private void btnG08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnG08ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnG08ActionPerformed

    private void btnG10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnG10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnG10ActionPerformed

    private void btnG11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnG11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnG11ActionPerformed

    private void btnG13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnG13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnG13ActionPerformed

    private void btnG14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnG14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnG14ActionPerformed

    private void btnG16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnG16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnG16ActionPerformed

    private void btnG17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnG17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnG17ActionPerformed

    private void btnH01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnH01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnH01ActionPerformed

    private void btnH03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnH03ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnH03ActionPerformed

    private void btnH05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnH05ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnH05ActionPerformed

    private void btnH07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnH07ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnH07ActionPerformed

    private void btnH09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnH09ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnH09ActionPerformed

    private void btnH11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnH11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnH11ActionPerformed

    private void btnH13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnH13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnH13ActionPerformed

    private void btnH15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnH15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnH15ActionPerformed

    private void btnH17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnH17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnH17ActionPerformed

    private void btnI01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnI01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnI01ActionPerformed

    private void btnI02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnI02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnI02ActionPerformed

    private void btnI04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnI04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnI04ActionPerformed

    private void btnI05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnI05ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnI05ActionPerformed

    private void btnI07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnI07ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnI07ActionPerformed

    private void btnI08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnI08ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnI08ActionPerformed

    private void btnI10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnI10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnI10ActionPerformed

    private void btnI11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnI11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnI11ActionPerformed

    private void btnI13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnI13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnI13ActionPerformed

    private void btnI14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnI14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnI14ActionPerformed

    private void btnI16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnI16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnI16ActionPerformed

    private void btnI17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnI17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnI17ActionPerformed

    private void btnJ01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJ01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnJ01ActionPerformed

    private void btnJ03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJ03ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnJ03ActionPerformed

    private void btnJ05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJ05ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnJ05ActionPerformed

    private void btnJ07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJ07ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnJ07ActionPerformed

    private void btnJ09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJ09ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnJ09ActionPerformed

    private void btnJ11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJ11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnJ11ActionPerformed

    private void btnJ13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJ13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnJ13ActionPerformed

    private void btnJ15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJ15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnJ15ActionPerformed

    private void btnJ17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJ17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnJ17ActionPerformed

    private void btnK01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnK01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnK01ActionPerformed

    private void btnK02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnK02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnK02ActionPerformed

    private void btnK04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnK04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnK04ActionPerformed

    private void btnK05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnK05ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnK05ActionPerformed

    private void btnK07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnK07ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnK07ActionPerformed

    private void btnK08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnK08ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnK08ActionPerformed

    private void btnK10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnK10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnK10ActionPerformed

    private void btnK11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnK11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnK11ActionPerformed

    private void btnK13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnK13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnK13ActionPerformed

    private void btnK14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnK14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnK14ActionPerformed

    private void btnK16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnK16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnK16ActionPerformed

    private void btnK17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnK17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnK17ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seat2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seat2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seat2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seat2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Seat2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnA01;
    private javax.swing.JButton btnA02;
    private javax.swing.JButton btnA04;
    private javax.swing.JButton btnA05;
    private javax.swing.JButton btnA07;
    private javax.swing.JButton btnA08;
    private javax.swing.JButton btnA10;
    private javax.swing.JButton btnA11;
    private javax.swing.JButton btnA13;
    private javax.swing.JButton btnA14;
    private javax.swing.JButton btnA16;
    private javax.swing.JButton btnA17;
    private javax.swing.JButton btnAvailable;
    private javax.swing.JButton btnB01;
    private javax.swing.JButton btnB03;
    private javax.swing.JButton btnB05;
    private javax.swing.JButton btnB07;
    private javax.swing.JButton btnB09;
    private javax.swing.JButton btnB11;
    private javax.swing.JButton btnB13;
    private javax.swing.JButton btnB15;
    private javax.swing.JButton btnB17;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnC01;
    private javax.swing.JButton btnC02;
    private javax.swing.JButton btnC04;
    private javax.swing.JButton btnC05;
    private javax.swing.JButton btnC07;
    private javax.swing.JButton btnC08;
    private javax.swing.JButton btnC10;
    private javax.swing.JButton btnC11;
    private javax.swing.JButton btnC13;
    private javax.swing.JButton btnC14;
    private javax.swing.JButton btnC16;
    private javax.swing.JButton btnC17;
    private javax.swing.JButton btnD01;
    private javax.swing.JButton btnD03;
    private javax.swing.JButton btnD05;
    private javax.swing.JButton btnD07;
    private javax.swing.JButton btnD09;
    private javax.swing.JButton btnD11;
    private javax.swing.JButton btnD13;
    private javax.swing.JButton btnD15;
    private javax.swing.JButton btnD17;
    private javax.swing.JButton btnE01;
    private javax.swing.JButton btnE02;
    private javax.swing.JButton btnE04;
    private javax.swing.JButton btnE05;
    private javax.swing.JButton btnE07;
    private javax.swing.JButton btnE08;
    private javax.swing.JButton btnE10;
    private javax.swing.JButton btnE11;
    private javax.swing.JButton btnE13;
    private javax.swing.JButton btnE14;
    private javax.swing.JButton btnE16;
    private javax.swing.JButton btnE17;
    private javax.swing.JButton btnF01;
    private javax.swing.JButton btnF03;
    private javax.swing.JButton btnF05;
    private javax.swing.JButton btnF07;
    private javax.swing.JButton btnF09;
    private javax.swing.JButton btnF11;
    private javax.swing.JButton btnF13;
    private javax.swing.JButton btnF15;
    private javax.swing.JButton btnF17;
    private javax.swing.JButton btnG01;
    private javax.swing.JButton btnG02;
    private javax.swing.JButton btnG04;
    private javax.swing.JButton btnG05;
    private javax.swing.JButton btnG07;
    private javax.swing.JButton btnG08;
    private javax.swing.JButton btnG10;
    private javax.swing.JButton btnG11;
    private javax.swing.JButton btnG13;
    private javax.swing.JButton btnG14;
    private javax.swing.JButton btnG16;
    private javax.swing.JButton btnG17;
    private javax.swing.JButton btnH01;
    private javax.swing.JButton btnH03;
    private javax.swing.JButton btnH05;
    private javax.swing.JButton btnH07;
    private javax.swing.JButton btnH09;
    private javax.swing.JButton btnH11;
    private javax.swing.JButton btnH13;
    private javax.swing.JButton btnH15;
    private javax.swing.JButton btnH17;
    private javax.swing.JButton btnI01;
    private javax.swing.JButton btnI02;
    private javax.swing.JButton btnI04;
    private javax.swing.JButton btnI05;
    private javax.swing.JButton btnI07;
    private javax.swing.JButton btnI08;
    private javax.swing.JButton btnI10;
    private javax.swing.JButton btnI11;
    private javax.swing.JButton btnI13;
    private javax.swing.JButton btnI14;
    private javax.swing.JButton btnI16;
    private javax.swing.JButton btnI17;
    private javax.swing.JButton btnJ01;
    private javax.swing.JButton btnJ03;
    private javax.swing.JButton btnJ05;
    private javax.swing.JButton btnJ07;
    private javax.swing.JButton btnJ09;
    private javax.swing.JButton btnJ11;
    private javax.swing.JButton btnJ13;
    private javax.swing.JButton btnJ15;
    private javax.swing.JButton btnJ17;
    private javax.swing.JButton btnK01;
    private javax.swing.JButton btnK02;
    private javax.swing.JButton btnK04;
    private javax.swing.JButton btnK05;
    private javax.swing.JButton btnK07;
    private javax.swing.JButton btnK08;
    private javax.swing.JButton btnK10;
    private javax.swing.JButton btnK11;
    private javax.swing.JButton btnK13;
    private javax.swing.JButton btnK14;
    private javax.swing.JButton btnK16;
    private javax.swing.JButton btnK17;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnSelected;
    private javax.swing.JButton btnTwin1;
    private javax.swing.JButton btnTwin2;
    private javax.swing.JButton btnUnavailable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
