package cinemaswingtest1;

import java.awt.Color;

public class Seat1 extends javax.swing.JFrame {

    private int a01,a02,a04,a05,a07,a08,a10,a11,
            b01,b03,b05,b07,b09,b11,
            c01,c02,c04,c05,c07,c08,c10,c11,
            d01,d03,d05,d07,d09,d11,
            e01,e02,e04,e05,e07,e08,e10,e11,
            f01,f03,f05,f07,f09,f11,
            g01,g02,g04,g05,g07,g08,g10,g11,
            h01,h03,h05,h07,h09,h11,
            i01,i02,i04,i05,i07,i08,i10,i11,
            j01,j03,j05,j07,j09,j11,
            k01,k02,k04,k05,k07,k08,k10,k11;

    /**
     * Creates new form Seat
     */
    public Seat1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnA01 = new javax.swing.JButton();
        btnA02 = new javax.swing.JButton();
        btnA05 = new javax.swing.JButton();
        btnA04 = new javax.swing.JButton();
        btnA08 = new javax.swing.JButton();
        btnA07 = new javax.swing.JButton();
        btnA11 = new javax.swing.JButton();
        btnA10 = new javax.swing.JButton();
        btnB01 = new javax.swing.JButton();
        btnB11 = new javax.swing.JButton();
        btnB03 = new javax.swing.JButton();
        btnB05 = new javax.swing.JButton();
        btnB07 = new javax.swing.JButton();
        btnB09 = new javax.swing.JButton();
        btnC10 = new javax.swing.JButton();
        btnC01 = new javax.swing.JButton();
        btnC02 = new javax.swing.JButton();
        btnD01 = new javax.swing.JButton();
        btnD11 = new javax.swing.JButton();
        btnC05 = new javax.swing.JButton();
        btnD03 = new javax.swing.JButton();
        btnD05 = new javax.swing.JButton();
        btnC04 = new javax.swing.JButton();
        btnD07 = new javax.swing.JButton();
        btnC08 = new javax.swing.JButton();
        btnD09 = new javax.swing.JButton();
        btnC07 = new javax.swing.JButton();
        btnC11 = new javax.swing.JButton();
        btnE10 = new javax.swing.JButton();
        btnE01 = new javax.swing.JButton();
        btnE02 = new javax.swing.JButton();
        btnF01 = new javax.swing.JButton();
        btnF11 = new javax.swing.JButton();
        btnE05 = new javax.swing.JButton();
        btnF03 = new javax.swing.JButton();
        btnF05 = new javax.swing.JButton();
        btnE04 = new javax.swing.JButton();
        btnF07 = new javax.swing.JButton();
        btnE08 = new javax.swing.JButton();
        btnF09 = new javax.swing.JButton();
        btnE07 = new javax.swing.JButton();
        btnE11 = new javax.swing.JButton();
        btnG10 = new javax.swing.JButton();
        btnG01 = new javax.swing.JButton();
        btnG02 = new javax.swing.JButton();
        btnH01 = new javax.swing.JButton();
        btnH11 = new javax.swing.JButton();
        btnG05 = new javax.swing.JButton();
        btnH03 = new javax.swing.JButton();
        btnH05 = new javax.swing.JButton();
        btnG04 = new javax.swing.JButton();
        btnH07 = new javax.swing.JButton();
        btnG08 = new javax.swing.JButton();
        btnH09 = new javax.swing.JButton();
        btnG07 = new javax.swing.JButton();
        btnG11 = new javax.swing.JButton();
        btnI10 = new javax.swing.JButton();
        btnI01 = new javax.swing.JButton();
        btnI02 = new javax.swing.JButton();
        btnJ01 = new javax.swing.JButton();
        btnJ11 = new javax.swing.JButton();
        btnI05 = new javax.swing.JButton();
        btnJ03 = new javax.swing.JButton();
        btnJ05 = new javax.swing.JButton();
        btnI04 = new javax.swing.JButton();
        btnJ07 = new javax.swing.JButton();
        btnI08 = new javax.swing.JButton();
        btnJ09 = new javax.swing.JButton();
        btnI07 = new javax.swing.JButton();
        btnI11 = new javax.swing.JButton();
        btnK10 = new javax.swing.JButton();
        btnK01 = new javax.swing.JButton();
        btnK02 = new javax.swing.JButton();
        btnK05 = new javax.swing.JButton();
        btnK04 = new javax.swing.JButton();
        btnK08 = new javax.swing.JButton();
        btnK07 = new javax.swing.JButton();
        btnK11 = new javax.swing.JButton();
        btnSelected = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnTwin1 = new javax.swing.JButton();
        btnTwin2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnAvailable = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnUnavailable = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Seat");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 70, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("S C R E E N");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 57, 1030, -1));

        btnNext.setText("NEXT");
        getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(978, 602, 60, 25));

        btnBack.setText("BACK");
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 602, -1, 25));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinemaswingtest1/image/mainmenu/logo (1).png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, -1));

        btnA01.setBackground(new java.awt.Color(255, 204, 255));
        btnA01.setText("A01");
        btnA01.setPreferredSize(new java.awt.Dimension(55, 25));
        btnA01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA01ActionPerformed(evt);
            }
        });
        getContentPane().add(btnA01, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 92, -1, -1));

        btnA02.setBackground(new java.awt.Color(255, 204, 255));
        btnA02.setText("A02");
        btnA02.setPreferredSize(new java.awt.Dimension(55, 25));
        btnA02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA02ActionPerformed(evt);
            }
        });
        getContentPane().add(btnA02, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 92, -1, -1));

        btnA05.setBackground(new java.awt.Color(255, 204, 255));
        btnA05.setText("A05");
        btnA05.setPreferredSize(new java.awt.Dimension(55, 25));
        btnA05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA05ActionPerformed(evt);
            }
        });
        getContentPane().add(btnA05, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 92, -1, -1));

        btnA04.setBackground(new java.awt.Color(255, 204, 255));
        btnA04.setText("A04");
        btnA04.setPreferredSize(new java.awt.Dimension(55, 25));
        btnA04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA04ActionPerformed(evt);
            }
        });
        getContentPane().add(btnA04, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 92, -1, -1));

        btnA08.setBackground(new java.awt.Color(255, 204, 255));
        btnA08.setText("A08");
        btnA08.setPreferredSize(new java.awt.Dimension(55, 25));
        btnA08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA08ActionPerformed(evt);
            }
        });
        getContentPane().add(btnA08, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 92, -1, -1));

        btnA07.setBackground(new java.awt.Color(255, 204, 255));
        btnA07.setText("A07");
        btnA07.setPreferredSize(new java.awt.Dimension(55, 25));
        btnA07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA07ActionPerformed(evt);
            }
        });
        getContentPane().add(btnA07, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 92, -1, -1));

        btnA11.setBackground(new java.awt.Color(255, 204, 255));
        btnA11.setText("A11");
        btnA11.setPreferredSize(new java.awt.Dimension(55, 25));
        btnA11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA11ActionPerformed(evt);
            }
        });
        getContentPane().add(btnA11, new org.netbeans.lib.awtextra.AbsoluteConstraints(801, 92, -1, -1));

        btnA10.setBackground(new java.awt.Color(255, 204, 255));
        btnA10.setText("A10");
        btnA10.setPreferredSize(new java.awt.Dimension(55, 25));
        btnA10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA10ActionPerformed(evt);
            }
        });
        getContentPane().add(btnA10, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 92, -1, -1));

        btnB01.setText("B01");
        btnB01.setPreferredSize(new java.awt.Dimension(55, 25));
        btnB01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnB01ActionPerformed(evt);
            }
        });
        getContentPane().add(btnB01, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 135, -1, -1));

        btnB11.setText("B11");
        btnB11.setPreferredSize(new java.awt.Dimension(55, 25));
        btnB11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnB11ActionPerformed(evt);
            }
        });
        getContentPane().add(btnB11, new org.netbeans.lib.awtextra.AbsoluteConstraints(801, 135, -1, -1));

        btnB03.setText("B03");
        btnB03.setPreferredSize(new java.awt.Dimension(55, 25));
        btnB03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnB03ActionPerformed(evt);
            }
        });
        getContentPane().add(btnB03, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 135, -1, -1));

        btnB05.setText("B05");
        btnB05.setPreferredSize(new java.awt.Dimension(55, 25));
        btnB05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnB05ActionPerformed(evt);
            }
        });
        getContentPane().add(btnB05, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 135, -1, -1));

        btnB07.setText("B07");
        btnB07.setPreferredSize(new java.awt.Dimension(55, 25));
        btnB07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnB07ActionPerformed(evt);
            }
        });
        getContentPane().add(btnB07, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 135, -1, -1));

        btnB09.setText("B09");
        btnB09.setPreferredSize(new java.awt.Dimension(55, 25));
        btnB09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnB09ActionPerformed(evt);
            }
        });
        getContentPane().add(btnB09, new org.netbeans.lib.awtextra.AbsoluteConstraints(679, 135, -1, -1));

        btnC10.setBackground(new java.awt.Color(255, 204, 255));
        btnC10.setText("C10");
        btnC10.setPreferredSize(new java.awt.Dimension(55, 25));
        btnC10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnC10ActionPerformed(evt);
            }
        });
        getContentPane().add(btnC10, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 178, -1, -1));

        btnC01.setBackground(new java.awt.Color(255, 204, 255));
        btnC01.setText("C01");
        btnC01.setPreferredSize(new java.awt.Dimension(55, 25));
        btnC01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnC01ActionPerformed(evt);
            }
        });
        getContentPane().add(btnC01, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 178, -1, -1));

        btnC02.setBackground(new java.awt.Color(255, 204, 255));
        btnC02.setText("C02");
        btnC02.setPreferredSize(new java.awt.Dimension(55, 25));
        btnC02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnC02ActionPerformed(evt);
            }
        });
        getContentPane().add(btnC02, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 178, -1, -1));

        btnD01.setText("D01");
        btnD01.setPreferredSize(new java.awt.Dimension(55, 25));
        btnD01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD01ActionPerformed(evt);
            }
        });
        getContentPane().add(btnD01, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 221, -1, -1));

        btnD11.setText("D11");
        btnD11.setPreferredSize(new java.awt.Dimension(55, 25));
        btnD11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD11ActionPerformed(evt);
            }
        });
        getContentPane().add(btnD11, new org.netbeans.lib.awtextra.AbsoluteConstraints(801, 221, -1, -1));

        btnC05.setBackground(new java.awt.Color(255, 204, 255));
        btnC05.setText("C05");
        btnC05.setPreferredSize(new java.awt.Dimension(55, 25));
        btnC05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnC05ActionPerformed(evt);
            }
        });
        getContentPane().add(btnC05, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 178, -1, -1));

        btnD03.setText("D03");
        btnD03.setPreferredSize(new java.awt.Dimension(55, 25));
        btnD03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD03ActionPerformed(evt);
            }
        });
        getContentPane().add(btnD03, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 221, -1, -1));

        btnD05.setText("D05");
        btnD05.setPreferredSize(new java.awt.Dimension(55, 25));
        btnD05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD05ActionPerformed(evt);
            }
        });
        getContentPane().add(btnD05, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 221, -1, -1));

        btnC04.setBackground(new java.awt.Color(255, 204, 255));
        btnC04.setText("C04");
        btnC04.setPreferredSize(new java.awt.Dimension(55, 25));
        btnC04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnC04ActionPerformed(evt);
            }
        });
        getContentPane().add(btnC04, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 178, -1, -1));

        btnD07.setText("D07");
        btnD07.setPreferredSize(new java.awt.Dimension(55, 25));
        btnD07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD07ActionPerformed(evt);
            }
        });
        getContentPane().add(btnD07, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 221, -1, -1));

        btnC08.setBackground(new java.awt.Color(255, 204, 255));
        btnC08.setText("C08");
        btnC08.setPreferredSize(new java.awt.Dimension(55, 25));
        btnC08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnC08ActionPerformed(evt);
            }
        });
        getContentPane().add(btnC08, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 178, -1, -1));

        btnD09.setText("D09");
        btnD09.setPreferredSize(new java.awt.Dimension(55, 25));
        btnD09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD09ActionPerformed(evt);
            }
        });
        getContentPane().add(btnD09, new org.netbeans.lib.awtextra.AbsoluteConstraints(679, 221, -1, -1));

        btnC07.setBackground(new java.awt.Color(255, 204, 255));
        btnC07.setText("C07");
        btnC07.setPreferredSize(new java.awt.Dimension(55, 25));
        btnC07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnC07ActionPerformed(evt);
            }
        });
        getContentPane().add(btnC07, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 178, -1, -1));

        btnC11.setBackground(new java.awt.Color(255, 204, 255));
        btnC11.setText("C11");
        btnC11.setPreferredSize(new java.awt.Dimension(55, 25));
        btnC11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnC11ActionPerformed(evt);
            }
        });
        getContentPane().add(btnC11, new org.netbeans.lib.awtextra.AbsoluteConstraints(801, 178, -1, -1));

        btnE10.setBackground(new java.awt.Color(255, 204, 255));
        btnE10.setText("E10");
        btnE10.setPreferredSize(new java.awt.Dimension(55, 25));
        btnE10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnE10ActionPerformed(evt);
            }
        });
        getContentPane().add(btnE10, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 264, -1, -1));

        btnE01.setBackground(new java.awt.Color(255, 204, 255));
        btnE01.setText("E01");
        btnE01.setPreferredSize(new java.awt.Dimension(55, 25));
        btnE01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnE01ActionPerformed(evt);
            }
        });
        getContentPane().add(btnE01, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 264, -1, -1));

        btnE02.setBackground(new java.awt.Color(255, 204, 255));
        btnE02.setText("E02");
        btnE02.setPreferredSize(new java.awt.Dimension(55, 25));
        btnE02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnE02ActionPerformed(evt);
            }
        });
        getContentPane().add(btnE02, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 264, -1, -1));

        btnF01.setText("F01");
        btnF01.setPreferredSize(new java.awt.Dimension(55, 25));
        btnF01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnF01ActionPerformed(evt);
            }
        });
        getContentPane().add(btnF01, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 307, -1, -1));

        btnF11.setText("F11");
        btnF11.setPreferredSize(new java.awt.Dimension(55, 25));
        btnF11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnF11ActionPerformed(evt);
            }
        });
        getContentPane().add(btnF11, new org.netbeans.lib.awtextra.AbsoluteConstraints(801, 307, -1, -1));

        btnE05.setBackground(new java.awt.Color(255, 204, 255));
        btnE05.setText("E05");
        btnE05.setPreferredSize(new java.awt.Dimension(55, 25));
        btnE05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnE05ActionPerformed(evt);
            }
        });
        getContentPane().add(btnE05, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 264, -1, -1));

        btnF03.setText("F03");
        btnF03.setPreferredSize(new java.awt.Dimension(55, 25));
        btnF03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnF03ActionPerformed(evt);
            }
        });
        getContentPane().add(btnF03, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 307, -1, -1));

        btnF05.setText("F05");
        btnF05.setPreferredSize(new java.awt.Dimension(55, 25));
        btnF05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnF05ActionPerformed(evt);
            }
        });
        getContentPane().add(btnF05, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 307, -1, -1));

        btnE04.setBackground(new java.awt.Color(255, 204, 255));
        btnE04.setText("E04");
        btnE04.setPreferredSize(new java.awt.Dimension(55, 25));
        btnE04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnE04ActionPerformed(evt);
            }
        });
        getContentPane().add(btnE04, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 264, -1, -1));

        btnF07.setText("F07");
        btnF07.setPreferredSize(new java.awt.Dimension(55, 25));
        btnF07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnF07ActionPerformed(evt);
            }
        });
        getContentPane().add(btnF07, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 307, -1, -1));

        btnE08.setBackground(new java.awt.Color(255, 204, 255));
        btnE08.setText("E08");
        btnE08.setPreferredSize(new java.awt.Dimension(55, 25));
        btnE08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnE08ActionPerformed(evt);
            }
        });
        getContentPane().add(btnE08, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 264, -1, -1));

        btnF09.setText("F09");
        btnF09.setPreferredSize(new java.awt.Dimension(55, 25));
        btnF09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnF09ActionPerformed(evt);
            }
        });
        getContentPane().add(btnF09, new org.netbeans.lib.awtextra.AbsoluteConstraints(679, 307, -1, -1));

        btnE07.setBackground(new java.awt.Color(255, 204, 255));
        btnE07.setText("E07");
        btnE07.setPreferredSize(new java.awt.Dimension(55, 25));
        btnE07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnE07ActionPerformed(evt);
            }
        });
        getContentPane().add(btnE07, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 264, -1, -1));

        btnE11.setBackground(new java.awt.Color(255, 204, 255));
        btnE11.setText("E11");
        btnE11.setPreferredSize(new java.awt.Dimension(55, 25));
        btnE11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnE11ActionPerformed(evt);
            }
        });
        getContentPane().add(btnE11, new org.netbeans.lib.awtextra.AbsoluteConstraints(801, 264, -1, -1));

        btnG10.setBackground(new java.awt.Color(255, 204, 255));
        btnG10.setText("G10");
        btnG10.setPreferredSize(new java.awt.Dimension(55, 25));
        btnG10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnG10ActionPerformed(evt);
            }
        });
        getContentPane().add(btnG10, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 350, -1, -1));

        btnG01.setBackground(new java.awt.Color(255, 204, 255));
        btnG01.setText("G01");
        btnG01.setPreferredSize(new java.awt.Dimension(55, 25));
        btnG01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnG01ActionPerformed(evt);
            }
        });
        getContentPane().add(btnG01, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 350, -1, -1));

        btnG02.setBackground(new java.awt.Color(255, 204, 255));
        btnG02.setText("G02");
        btnG02.setPreferredSize(new java.awt.Dimension(55, 25));
        btnG02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnG02ActionPerformed(evt);
            }
        });
        getContentPane().add(btnG02, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 350, -1, -1));

        btnH01.setText("H01");
        btnH01.setPreferredSize(new java.awt.Dimension(55, 25));
        btnH01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnH01ActionPerformed(evt);
            }
        });
        getContentPane().add(btnH01, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 393, -1, -1));

        btnH11.setText("H11");
        btnH11.setPreferredSize(new java.awt.Dimension(55, 25));
        btnH11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnH11ActionPerformed(evt);
            }
        });
        getContentPane().add(btnH11, new org.netbeans.lib.awtextra.AbsoluteConstraints(801, 393, -1, -1));

        btnG05.setBackground(new java.awt.Color(255, 204, 255));
        btnG05.setText("G05");
        btnG05.setPreferredSize(new java.awt.Dimension(55, 25));
        btnG05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnG05ActionPerformed(evt);
            }
        });
        getContentPane().add(btnG05, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 350, -1, -1));

        btnH03.setText("H03");
        btnH03.setPreferredSize(new java.awt.Dimension(55, 25));
        btnH03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnH03ActionPerformed(evt);
            }
        });
        getContentPane().add(btnH03, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 393, -1, -1));

        btnH05.setText("H05");
        btnH05.setPreferredSize(new java.awt.Dimension(55, 25));
        btnH05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnH05ActionPerformed(evt);
            }
        });
        getContentPane().add(btnH05, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 393, -1, -1));

        btnG04.setBackground(new java.awt.Color(255, 204, 255));
        btnG04.setText("G04");
        btnG04.setPreferredSize(new java.awt.Dimension(55, 25));
        btnG04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnG04ActionPerformed(evt);
            }
        });
        getContentPane().add(btnG04, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 350, -1, -1));

        btnH07.setText("H07");
        btnH07.setPreferredSize(new java.awt.Dimension(55, 25));
        btnH07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnH07ActionPerformed(evt);
            }
        });
        getContentPane().add(btnH07, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 393, -1, -1));

        btnG08.setBackground(new java.awt.Color(255, 204, 255));
        btnG08.setText("G08");
        btnG08.setPreferredSize(new java.awt.Dimension(55, 25));
        btnG08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnG08ActionPerformed(evt);
            }
        });
        getContentPane().add(btnG08, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 350, -1, -1));

        btnH09.setText("H09");
        btnH09.setPreferredSize(new java.awt.Dimension(55, 25));
        btnH09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnH09ActionPerformed(evt);
            }
        });
        getContentPane().add(btnH09, new org.netbeans.lib.awtextra.AbsoluteConstraints(679, 393, -1, -1));

        btnG07.setBackground(new java.awt.Color(255, 204, 255));
        btnG07.setText("G07");
        btnG07.setPreferredSize(new java.awt.Dimension(55, 25));
        btnG07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnG07ActionPerformed(evt);
            }
        });
        getContentPane().add(btnG07, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 350, -1, -1));

        btnG11.setBackground(new java.awt.Color(255, 204, 255));
        btnG11.setText("G11");
        btnG11.setPreferredSize(new java.awt.Dimension(55, 25));
        btnG11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnG11ActionPerformed(evt);
            }
        });
        getContentPane().add(btnG11, new org.netbeans.lib.awtextra.AbsoluteConstraints(801, 350, -1, -1));

        btnI10.setBackground(new java.awt.Color(255, 204, 255));
        btnI10.setText("I10");
        btnI10.setPreferredSize(new java.awt.Dimension(55, 25));
        btnI10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnI10ActionPerformed(evt);
            }
        });
        getContentPane().add(btnI10, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 436, -1, -1));

        btnI01.setBackground(new java.awt.Color(255, 204, 255));
        btnI01.setText("I01");
        btnI01.setPreferredSize(new java.awt.Dimension(55, 25));
        btnI01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnI01ActionPerformed(evt);
            }
        });
        getContentPane().add(btnI01, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 436, -1, -1));

        btnI02.setBackground(new java.awt.Color(255, 204, 255));
        btnI02.setText("I02");
        btnI02.setPreferredSize(new java.awt.Dimension(55, 25));
        btnI02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnI02ActionPerformed(evt);
            }
        });
        getContentPane().add(btnI02, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 436, -1, -1));

        btnJ01.setText("J01");
        btnJ01.setPreferredSize(new java.awt.Dimension(55, 25));
        btnJ01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJ01ActionPerformed(evt);
            }
        });
        getContentPane().add(btnJ01, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 479, -1, -1));

        btnJ11.setText("J11");
        btnJ11.setPreferredSize(new java.awt.Dimension(55, 25));
        btnJ11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJ11ActionPerformed(evt);
            }
        });
        getContentPane().add(btnJ11, new org.netbeans.lib.awtextra.AbsoluteConstraints(801, 479, -1, -1));

        btnI05.setBackground(new java.awt.Color(255, 204, 255));
        btnI05.setText("I05");
        btnI05.setPreferredSize(new java.awt.Dimension(55, 25));
        btnI05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnI05ActionPerformed(evt);
            }
        });
        getContentPane().add(btnI05, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 436, -1, -1));

        btnJ03.setText("J03");
        btnJ03.setPreferredSize(new java.awt.Dimension(55, 25));
        btnJ03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJ03ActionPerformed(evt);
            }
        });
        getContentPane().add(btnJ03, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 479, -1, -1));

        btnJ05.setText("J05");
        btnJ05.setPreferredSize(new java.awt.Dimension(55, 25));
        btnJ05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJ05ActionPerformed(evt);
            }
        });
        getContentPane().add(btnJ05, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 479, -1, -1));

        btnI04.setBackground(new java.awt.Color(255, 204, 255));
        btnI04.setText("I04");
        btnI04.setPreferredSize(new java.awt.Dimension(55, 25));
        btnI04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnI04ActionPerformed(evt);
            }
        });
        getContentPane().add(btnI04, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 436, -1, -1));

        btnJ07.setText("J07");
        btnJ07.setPreferredSize(new java.awt.Dimension(55, 25));
        btnJ07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJ07ActionPerformed(evt);
            }
        });
        getContentPane().add(btnJ07, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 479, -1, -1));

        btnI08.setBackground(new java.awt.Color(255, 204, 255));
        btnI08.setText("I08");
        btnI08.setPreferredSize(new java.awt.Dimension(55, 25));
        btnI08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnI08ActionPerformed(evt);
            }
        });
        getContentPane().add(btnI08, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 436, -1, -1));

        btnJ09.setText("J09");
        btnJ09.setPreferredSize(new java.awt.Dimension(55, 25));
        btnJ09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJ09ActionPerformed(evt);
            }
        });
        getContentPane().add(btnJ09, new org.netbeans.lib.awtextra.AbsoluteConstraints(679, 479, -1, -1));

        btnI07.setBackground(new java.awt.Color(255, 204, 255));
        btnI07.setText("I07");
        btnI07.setPreferredSize(new java.awt.Dimension(55, 25));
        btnI07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnI07ActionPerformed(evt);
            }
        });
        getContentPane().add(btnI07, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 436, -1, -1));

        btnI11.setBackground(new java.awt.Color(255, 204, 255));
        btnI11.setText("I11");
        btnI11.setPreferredSize(new java.awt.Dimension(55, 25));
        btnI11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnI11ActionPerformed(evt);
            }
        });
        getContentPane().add(btnI11, new org.netbeans.lib.awtextra.AbsoluteConstraints(801, 436, -1, -1));

        btnK10.setBackground(new java.awt.Color(255, 204, 255));
        btnK10.setText("K10");
        btnK10.setPreferredSize(new java.awt.Dimension(55, 25));
        btnK10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK10ActionPerformed(evt);
            }
        });
        getContentPane().add(btnK10, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 522, -1, -1));

        btnK01.setBackground(new java.awt.Color(255, 204, 255));
        btnK01.setText("K01");
        btnK01.setPreferredSize(new java.awt.Dimension(55, 25));
        btnK01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK01ActionPerformed(evt);
            }
        });
        getContentPane().add(btnK01, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 522, -1, -1));

        btnK02.setBackground(new java.awt.Color(255, 204, 255));
        btnK02.setText("K02");
        btnK02.setPreferredSize(new java.awt.Dimension(55, 25));
        btnK02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK02ActionPerformed(evt);
            }
        });
        getContentPane().add(btnK02, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 522, -1, -1));

        btnK05.setBackground(new java.awt.Color(255, 204, 255));
        btnK05.setText("K05");
        btnK05.setPreferredSize(new java.awt.Dimension(55, 25));
        btnK05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK05ActionPerformed(evt);
            }
        });
        getContentPane().add(btnK05, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 522, -1, -1));

        btnK04.setBackground(new java.awt.Color(255, 204, 255));
        btnK04.setText("K04");
        btnK04.setPreferredSize(new java.awt.Dimension(55, 25));
        btnK04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK04ActionPerformed(evt);
            }
        });
        getContentPane().add(btnK04, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 522, -1, -1));

        btnK08.setBackground(new java.awt.Color(255, 204, 255));
        btnK08.setText("K08");
        btnK08.setPreferredSize(new java.awt.Dimension(55, 25));
        btnK08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK08ActionPerformed(evt);
            }
        });
        getContentPane().add(btnK08, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 522, -1, -1));

        btnK07.setBackground(new java.awt.Color(255, 204, 255));
        btnK07.setText("K07");
        btnK07.setPreferredSize(new java.awt.Dimension(55, 25));
        btnK07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK07ActionPerformed(evt);
            }
        });
        getContentPane().add(btnK07, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 522, -1, -1));

        btnK11.setBackground(new java.awt.Color(255, 204, 255));
        btnK11.setText("K11");
        btnK11.setPreferredSize(new java.awt.Dimension(55, 25));
        btnK11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnK11ActionPerformed(evt);
            }
        });
        getContentPane().add(btnK11, new org.netbeans.lib.awtextra.AbsoluteConstraints(801, 522, -1, -1));

        btnSelected.setBackground(new java.awt.Color(255, 255, 0));
        btnSelected.setPreferredSize(new java.awt.Dimension(55, 25));
        getContentPane().add(btnSelected, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 604, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Selected");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 602, 50, 30));

        btnTwin1.setBackground(new java.awt.Color(255, 204, 255));
        btnTwin1.setPreferredSize(new java.awt.Dimension(55, 25));
        getContentPane().add(btnTwin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 604, -1, -1));

        btnTwin2.setBackground(new java.awt.Color(255, 204, 255));
        btnTwin2.setPreferredSize(new java.awt.Dimension(55, 25));
        getContentPane().add(btnTwin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 604, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Twin");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 604, -1, 25));

        btnAvailable.setPreferredSize(new java.awt.Dimension(55, 25));
        getContentPane().add(btnAvailable, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 604, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Available");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 604, 50, 25));

        btnUnavailable.setBackground(new java.awt.Color(102, 102, 102));
        btnUnavailable.setPreferredSize(new java.awt.Dimension(55, 25));
        getContentPane().add(btnUnavailable, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 602, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Unavailable");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 602, 60, 25));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinemaswingtest1/image/mainmenu/dark grey (2).jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnA01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA01ActionPerformed
        if (a01 == 1) {
            btnA01.setBackground(new Color(255, 204, 255));
            btnA02.setBackground(new Color(255, 204, 255));
            a01 = 0;
        }
        else if (a01 == 0) {
            btnA01.setBackground(Color.YELLOW);
            btnA02.setBackground(Color.YELLOW);
            a01 = 1;
        }
    }//GEN-LAST:event_btnA01ActionPerformed

    private void btnA02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA02ActionPerformed
        if (a01 == 1) {
            btnA01.setBackground(new Color(255, 204, 255));
            btnA02.setBackground(new Color(255, 204, 255));
            a01 = 0;
        }
        else if (a01 == 0) {
            btnA01.setBackground(Color.YELLOW);
            btnA02.setBackground(Color.YELLOW);
            a01 = 1;
        }
    }//GEN-LAST:event_btnA02ActionPerformed

    private void btnA04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA04ActionPerformed
        if (a04 == 1) {
            btnA04.setBackground(new Color(255, 204, 255));
            btnA05.setBackground(new Color(255, 204, 255));
            a04 = 0;
        }
        else if (a04 == 0) {
            btnA04.setBackground(Color.YELLOW);
            btnA05.setBackground(Color.YELLOW);
            a04 = 1;
        }
    }//GEN-LAST:event_btnA04ActionPerformed

    private void btnA05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA05ActionPerformed
        if (a04 == 1) {
            btnA04.setBackground(new Color(255, 204, 255));
            btnA05.setBackground(new Color(255, 204, 255));
            a04 = 0;
        }
        else if (a04 == 0) {
            btnA04.setBackground(Color.YELLOW);
            btnA05.setBackground(Color.YELLOW);
            a04 = 1;
        }
    }//GEN-LAST:event_btnA05ActionPerformed

    private void btnA07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA07ActionPerformed
        if (a07 == 1) {
            btnA07.setBackground(new Color(255, 204, 255));
            btnA08.setBackground(new Color(255, 204, 255));
            a07 = 0;
        }
        else if (a07 == 0) {
            btnA07.setBackground(Color.YELLOW);
            btnA08.setBackground(Color.YELLOW);
            a07 = 1;
        }
    }//GEN-LAST:event_btnA07ActionPerformed

    private void btnA08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA08ActionPerformed
        if (a07 == 1) {
            btnA07.setBackground(new Color(255, 204, 255));
            btnA08.setBackground(new Color(255, 204, 255));
            a07 = 0;
        }
        else if (a07 == 0) {
            btnA07.setBackground(Color.YELLOW);
            btnA08.setBackground(Color.YELLOW);
            a07 = 1;
        }
    }//GEN-LAST:event_btnA08ActionPerformed

    private void btnA10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA10ActionPerformed
        if (a10 == 1) {
            btnA10.setBackground(new Color(255, 204, 255));
            btnA11.setBackground(new Color(255, 204, 255));
            a10 = 0;
        }
        else if (a10 == 0) {
            btnA10.setBackground(Color.YELLOW);
            btnA11.setBackground(Color.YELLOW);
            a10 = 1;
        }
    }//GEN-LAST:event_btnA10ActionPerformed

    private void btnA11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA11ActionPerformed
        if (a10 == 1) {
            btnA10.setBackground(new Color(255, 204, 255));
            btnA11.setBackground(new Color(255, 204, 255));
            a10 = 0;
        }
        else if (a10 == 0) {
            btnA10.setBackground(Color.YELLOW);
            btnA11.setBackground(Color.YELLOW);
            a10 = 1;
        }
    }//GEN-LAST:event_btnA11ActionPerformed

    private void btnB01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB01ActionPerformed
        if (b01 == 1) {
            btnB01.setBackground(Color.LIGHT_GRAY);
            b01 = 0;
        }
        else if (b01 == 0) {
            btnB01.setBackground(Color.YELLOW);
            b01 = 1;
        }
    }//GEN-LAST:event_btnB01ActionPerformed

    private void btnB03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB03ActionPerformed
        if (b03 == 1) {
            btnB03.setBackground(Color.LIGHT_GRAY);
            b03 = 0;
        }
        else if (b03 == 0) {
            btnB03.setBackground(Color.YELLOW);
            b03 = 1;
        }
    }//GEN-LAST:event_btnB03ActionPerformed

    private void btnB05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB05ActionPerformed
        if (b05 == 1) {
            btnB05.setBackground(Color.LIGHT_GRAY);
            b05 = 0;
        }
        else if (b05 == 0) {
            btnB05.setBackground(Color.YELLOW);
            b05 = 1;
        }
    }//GEN-LAST:event_btnB05ActionPerformed

    private void btnB07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB07ActionPerformed
        if (b07 == 1) {
            btnB07.setBackground(Color.LIGHT_GRAY);
            b07 = 0;
        }
        else if (b07 == 0) {
            btnB07.setBackground(Color.YELLOW);
            b07 = 1;
        }
    }//GEN-LAST:event_btnB07ActionPerformed

    private void btnB09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB09ActionPerformed
        if (b09 == 1) {
            btnB09.setBackground(Color.LIGHT_GRAY);
            b09 = 0;
        }
        else if (b09 == 0) {
            btnB09.setBackground(Color.YELLOW);
            b09 = 1;
        }
    }//GEN-LAST:event_btnB09ActionPerformed

    private void btnB11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB11ActionPerformed
        if (b11 == 1) {
            btnB11.setBackground(Color.LIGHT_GRAY);
            b11 = 0;
        }
        else if (b11 == 0) {
            btnB11.setBackground(Color.YELLOW);
            b11 = 1;
        }
    }//GEN-LAST:event_btnB11ActionPerformed

    private void btnC01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC01ActionPerformed
        if (c01 == 1) {
            btnC01.setBackground(new Color(255, 204, 255));
            btnC02.setBackground(new Color(255, 204, 255));
            c01 = 0;
        }
        else if (c01 == 0) {
            btnC01.setBackground(Color.YELLOW);
            btnC02.setBackground(Color.YELLOW);
            c01 = 1;
        }
    }//GEN-LAST:event_btnC01ActionPerformed

    private void btnC02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC02ActionPerformed
        if (c01 == 1) {
            btnC01.setBackground(new Color(255, 204, 255));
            btnC02.setBackground(new Color(255, 204, 255));
            c01 = 0;
        }
        else if (c01 == 0) {
            btnC01.setBackground(Color.YELLOW);
            btnC02.setBackground(Color.YELLOW);
            c01 = 1;
        }
    }//GEN-LAST:event_btnC02ActionPerformed

    private void btnC04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC04ActionPerformed
        if (c04 == 1) {
            btnC04.setBackground(new Color(255, 204, 255));
            btnC05.setBackground(new Color(255, 204, 255));
            c04 = 0;
        }
        else if (c04 == 0) {
            btnC04.setBackground(Color.YELLOW);
            btnC05.setBackground(Color.YELLOW);
            c04 = 1;
        }
    }//GEN-LAST:event_btnC04ActionPerformed

    private void btnC05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC05ActionPerformed
        if (c04 == 1) {
            btnC04.setBackground(new Color(255, 204, 255));
            btnC05.setBackground(new Color(255, 204, 255));
            c04 = 0;
        }
        else if (c04 == 0) {
            btnC04.setBackground(Color.YELLOW);
            btnC05.setBackground(Color.YELLOW);
            c04 = 1;
        }
    }//GEN-LAST:event_btnC05ActionPerformed

    private void btnC07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC07ActionPerformed
        if (c07 == 1) {
            btnC07.setBackground(new Color(255, 204, 255));
            btnC08.setBackground(new Color(255, 204, 255));
            c07 = 0;
        }
        else if (c07 == 0) {
            btnC07.setBackground(Color.YELLOW);
            btnC08.setBackground(Color.YELLOW);
            c07 = 1;
        }
    }//GEN-LAST:event_btnC07ActionPerformed

    private void btnC08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC08ActionPerformed
        if (c07 == 1) {
            btnC07.setBackground(new Color(255, 204, 255));
            btnC08.setBackground(new Color(255, 204, 255));
            c07 = 0;
        }
        else if (c07 == 0) {
            btnC07.setBackground(Color.YELLOW);
            btnC08.setBackground(Color.YELLOW);
            c07 = 1;
        }
    }//GEN-LAST:event_btnC08ActionPerformed

    private void btnC10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC10ActionPerformed
        if (c10 == 1) {
            btnC10.setBackground(new Color(255, 204, 255));
            btnC11.setBackground(new Color(255, 204, 255));
            c10 = 0;
        }
        else if (c10 == 0) {
            btnC10.setBackground(Color.YELLOW);
            btnC11.setBackground(Color.YELLOW);
            c10 = 1;
        }
    }//GEN-LAST:event_btnC10ActionPerformed

    private void btnC11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC11ActionPerformed
        if (c10 == 1) {
            btnC10.setBackground(new Color(255, 204, 255));
            btnC11.setBackground(new Color(255, 204, 255));
            c10 = 0;
        }
        else if (c10 == 0) {
            btnC10.setBackground(Color.YELLOW);
            btnC11.setBackground(Color.YELLOW);
            c10 = 1;
        }
    }//GEN-LAST:event_btnC11ActionPerformed

    private void btnD01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD01ActionPerformed
        if (d01 == 1) {
            btnD01.setBackground(Color.LIGHT_GRAY);
            d01 = 0;
        }
        else if (d01 == 0) {
            btnD01.setBackground(Color.YELLOW);
            d01 = 1;
        }
    }//GEN-LAST:event_btnD01ActionPerformed

    private void btnD03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD03ActionPerformed
        if (d03 == 1) {
            btnD03.setBackground(Color.LIGHT_GRAY);
            d03 = 0;
        }
        else if (d03 == 0) {
            btnD03.setBackground(Color.YELLOW);
            d03 = 1;
        }
    }//GEN-LAST:event_btnD03ActionPerformed

    private void btnD05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD05ActionPerformed
        if (d05 == 1) {
            btnD05.setBackground(Color.LIGHT_GRAY);
            d05 = 0;
        }
        else if (d05 == 0) {
            btnD05.setBackground(Color.YELLOW);
            d05 = 1;
        }
    }//GEN-LAST:event_btnD05ActionPerformed

    private void btnD07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD07ActionPerformed
        if (d07 == 1) {
            btnD07.setBackground(Color.LIGHT_GRAY);
            d07 = 0;
        }
        else if (d07 == 0) {
            btnD07.setBackground(Color.YELLOW);
            d07 = 1;
        }
    }//GEN-LAST:event_btnD07ActionPerformed

    private void btnD09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD09ActionPerformed
        if (d09 == 1) {
            btnD09.setBackground(Color.LIGHT_GRAY);
            d09 = 0;
        }
        else if (d09 == 0) {
            btnD09.setBackground(Color.YELLOW);
            d09 = 1;
        }
    }//GEN-LAST:event_btnD09ActionPerformed

    private void btnD11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD11ActionPerformed
        if (d11 == 1) {
            btnD11.setBackground(Color.LIGHT_GRAY);
            d11 = 0;
        }
        else if (d11 == 0) {
            btnD11.setBackground(Color.YELLOW);
            d11 = 1;
        }
    }//GEN-LAST:event_btnD11ActionPerformed

    private void btnE01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnE01ActionPerformed
        if (e01 == 1) {
            btnE01.setBackground(new Color(255, 204, 255));
            btnE02.setBackground(new Color(255, 204, 255));
            e01 = 0;
        }
        else if (e01 == 0) {
            btnE01.setBackground(Color.YELLOW);
            btnE02.setBackground(Color.YELLOW);
            e01 = 1;
        }
    }//GEN-LAST:event_btnE01ActionPerformed

    private void btnE02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnE02ActionPerformed
        if (e01 == 1) {
            btnE01.setBackground(new Color(255, 204, 255));
            btnE02.setBackground(new Color(255, 204, 255));
            e01 = 0;
        }
        else if (e01 == 0) {
            btnE01.setBackground(Color.YELLOW);
            btnE02.setBackground(Color.YELLOW);
            e01 = 1;
        }
    }//GEN-LAST:event_btnE02ActionPerformed

    private void btnE04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnE04ActionPerformed
        if (e04 == 1) {
            btnE04.setBackground(new Color(255, 204, 255));
            btnE05.setBackground(new Color(255, 204, 255));
            e04 = 0;
        }
        else if (e04 == 0) {
            btnE04.setBackground(Color.YELLOW);
            btnE05.setBackground(Color.YELLOW);
            e04 = 1;
        }
    }//GEN-LAST:event_btnE04ActionPerformed

    private void btnE05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnE05ActionPerformed
        if (e04 == 1) {
            btnE04.setBackground(new Color(255, 204, 255));
            btnE05.setBackground(new Color(255, 204, 255));
            e04 = 0;
        }
        else if (e04 == 0) {
            btnE04.setBackground(Color.YELLOW);
            btnE05.setBackground(Color.YELLOW);
            e04 = 1;
        }
    }//GEN-LAST:event_btnE05ActionPerformed

    private void btnE07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnE07ActionPerformed
        if (e07 == 1) {
            btnE07.setBackground(new Color(255, 204, 255));
            btnE08.setBackground(new Color(255, 204, 255));
            e07 = 0;
        }
        else if (e07 == 0) {
            btnE07.setBackground(Color.YELLOW);
            btnE08.setBackground(Color.YELLOW);
            e07 = 1;
        }
    }//GEN-LAST:event_btnE07ActionPerformed

    private void btnE08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnE08ActionPerformed
        if (e07 == 1) {
            btnE07.setBackground(new Color(255, 204, 255));
            btnE08.setBackground(new Color(255, 204, 255));
            e07 = 0;
        }
        else if (e07 == 0) {
            btnE07.setBackground(Color.YELLOW);
            btnE08.setBackground(Color.YELLOW);
            e07 = 1;
        }
    }//GEN-LAST:event_btnE08ActionPerformed

    private void btnE10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnE10ActionPerformed
        if (e10 == 1) {
            btnE10.setBackground(new Color(255, 204, 255));
            btnE11.setBackground(new Color(255, 204, 255));
            e10 = 0;
        }
        else if (e10 == 0) {
            btnE10.setBackground(Color.YELLOW);
            btnE11.setBackground(Color.YELLOW);
            e10 = 1;
        }
    }//GEN-LAST:event_btnE10ActionPerformed

    private void btnE11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnE11ActionPerformed
        if (e10 == 1) {
            btnE10.setBackground(new Color(255, 204, 255));
            btnE11.setBackground(new Color(255, 204, 255));
            e10 = 0;
        }
        else if (e10 == 0) {
            btnE10.setBackground(Color.YELLOW);
            btnE11.setBackground(Color.YELLOW);
            e10 = 1;
        }
    }//GEN-LAST:event_btnE11ActionPerformed

    private void btnF01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnF01ActionPerformed
        if (f01 == 1) {
            btnF01.setBackground(Color.LIGHT_GRAY);
            f01 = 0;
        }
        else if (f01 == 0) {
            btnF01.setBackground(Color.YELLOW);
            f01 = 1;
        }
    }//GEN-LAST:event_btnF01ActionPerformed

    private void btnF03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnF03ActionPerformed
        if (f03 == 1) {
            btnF03.setBackground(Color.LIGHT_GRAY);
            f03 = 0;
        }
        else if (f03 == 0) {
            btnF03.setBackground(Color.YELLOW);
            f03 = 1;
        }
    }//GEN-LAST:event_btnF03ActionPerformed

    private void btnF05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnF05ActionPerformed
        if (f05 == 1) {
            btnF05.setBackground(Color.LIGHT_GRAY);
            f05 = 0;
        }
        else if (f05 == 0) {
            btnF05.setBackground(Color.YELLOW);
            f05 = 1;
        }
    }//GEN-LAST:event_btnF05ActionPerformed

    private void btnF07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnF07ActionPerformed
        if (f07 == 1) {
            btnF07.setBackground(Color.LIGHT_GRAY);
            f07 = 0;
        }
        else if (f07 == 0) {
            btnF07.setBackground(Color.YELLOW);
            f07 = 1;
        }
    }//GEN-LAST:event_btnF07ActionPerformed

    private void btnF09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnF09ActionPerformed
        if (f09 == 1) {
            btnF09.setBackground(Color.LIGHT_GRAY);
            f09 = 0;
        }
        else if (f09 == 0) {
            btnF09.setBackground(Color.YELLOW);
            f09 = 1;
        }
    }//GEN-LAST:event_btnF09ActionPerformed

    private void btnF11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnF11ActionPerformed
        if (f11 == 1) {
            btnF11.setBackground(Color.LIGHT_GRAY);
            f11 = 0;
        }
        else if (f11 == 0) {
            btnF11.setBackground(Color.YELLOW);
            f11 = 1;
        }
    }//GEN-LAST:event_btnF11ActionPerformed

    private void btnG01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnG01ActionPerformed
        if (g01 == 1) {
            btnG01.setBackground(new Color(255, 204, 255));
            btnG02.setBackground(new Color(255, 204, 255));
            g01 = 0;
        }
        else if (g01 == 0) {
            btnG01.setBackground(Color.YELLOW);
            btnG02.setBackground(Color.YELLOW);
            g01 = 1;
        }
    }//GEN-LAST:event_btnG01ActionPerformed

    private void btnG02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnG02ActionPerformed
        if (g01 == 1) {
            btnG01.setBackground(new Color(255, 204, 255));
            btnG02.setBackground(new Color(255, 204, 255));
            g01 = 0;
        }
        else if (g01 == 0) {
            btnG01.setBackground(Color.YELLOW);
            btnG02.setBackground(Color.YELLOW);
            g01 = 1;
        }
    }//GEN-LAST:event_btnG02ActionPerformed

    private void btnG04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnG04ActionPerformed
        if (g04 == 1) {
            btnG04.setBackground(new Color(255, 204, 255));
            btnG05.setBackground(new Color(255, 204, 255));
            g04 = 0;
        }
        else if (g04 == 0) {
            btnG04.setBackground(Color.YELLOW);
            btnG05.setBackground(Color.YELLOW);
            g04 = 1;
        }
    }//GEN-LAST:event_btnG04ActionPerformed

    private void btnG05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnG05ActionPerformed
        if (g04 == 1) {
            btnG04.setBackground(new Color(255, 204, 255));
            btnG05.setBackground(new Color(255, 204, 255));
            g04 = 0;
        }
        else if (g04 == 0) {
            btnG04.setBackground(Color.YELLOW);
            btnG05.setBackground(Color.YELLOW);
            g04 = 1;
        }
    }//GEN-LAST:event_btnG05ActionPerformed

    private void btnG07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnG07ActionPerformed
        if (g07 == 1) {
            btnG07.setBackground(new Color(255, 204, 255));
            btnG08.setBackground(new Color(255, 204, 255));
            g07 = 0;
        }
        else if (g07 == 0) {
            btnG07.setBackground(Color.YELLOW);
            btnG08.setBackground(Color.YELLOW);
            g07 = 1;
        }
    }//GEN-LAST:event_btnG07ActionPerformed

    private void btnG08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnG08ActionPerformed
        if (g07 == 1) {
            btnG07.setBackground(new Color(255, 204, 255));
            btnG08.setBackground(new Color(255, 204, 255));
            g07 = 0;
        }
        else if (g07 == 0) {
            btnG07.setBackground(Color.YELLOW);
            btnG08.setBackground(Color.YELLOW);
            g07 = 1;
        }
    }//GEN-LAST:event_btnG08ActionPerformed

    private void btnG10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnG10ActionPerformed
        if (g10 == 1) {
            btnG10.setBackground(new Color(255, 204, 255));
            btnG11.setBackground(new Color(255, 204, 255));
            g10 = 0;
        }
        else if (g10 == 0) {
            btnG10.setBackground(Color.YELLOW);
            btnG11.setBackground(Color.YELLOW);
            g10 = 1;
        }
    }//GEN-LAST:event_btnG10ActionPerformed

    private void btnG11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnG11ActionPerformed
        if (g10 == 1) {
            btnG10.setBackground(new Color(255, 204, 255));
            btnG11.setBackground(new Color(255, 204, 255));
            g10 = 0;
        }
        else if (g10 == 0) {
            btnG10.setBackground(Color.YELLOW);
            btnG11.setBackground(Color.YELLOW);
            g10 = 1;
        }
    }//GEN-LAST:event_btnG11ActionPerformed

    private void btnH01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnH01ActionPerformed
        if (h01 == 1) {
            btnH01.setBackground(Color.LIGHT_GRAY);
            h01 = 0;
        }
        else if (h01 == 0) {
            btnH01.setBackground(Color.YELLOW);
            h01 = 1;
        }
    }//GEN-LAST:event_btnH01ActionPerformed

    private void btnH03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnH03ActionPerformed
        if (h03 == 1) {
            btnH03.setBackground(Color.LIGHT_GRAY);
            h03 = 0;
        }
        else if (h03 == 0) {
            btnH03.setBackground(Color.YELLOW);
            h03 = 1;
        }
    }//GEN-LAST:event_btnH03ActionPerformed

    private void btnH05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnH05ActionPerformed
        if (h05 == 1) {
            btnH05.setBackground(Color.LIGHT_GRAY);
            h05 = 0;
        }
        else if (h05 == 0) {
            btnH05.setBackground(Color.YELLOW);
            h05 = 1;
        }
    }//GEN-LAST:event_btnH05ActionPerformed

    private void btnH07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnH07ActionPerformed
        if (h07 == 1) {
            btnH07.setBackground(Color.LIGHT_GRAY);
            h07 = 0;
        }
        else if (h07 == 0) {
            btnH07.setBackground(Color.YELLOW);
            h07 = 1;
        }
    }//GEN-LAST:event_btnH07ActionPerformed

    private void btnH09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnH09ActionPerformed
        if (h09 == 1) {
            btnH09.setBackground(Color.LIGHT_GRAY);
            h09 = 0;
        }
        else if (h09 == 0) {
            btnH09.setBackground(Color.YELLOW);
            h09 = 1;
        }
    }//GEN-LAST:event_btnH09ActionPerformed

    private void btnH11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnH11ActionPerformed
        if (h11 == 1) {
            btnH11.setBackground(Color.LIGHT_GRAY);
            h11 = 0;
        }
        else if (h11 == 0) {
            btnH11.setBackground(Color.YELLOW);
            h11 = 1;
        }
    }//GEN-LAST:event_btnH11ActionPerformed

    private void btnI01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnI01ActionPerformed
        if (i01 == 1) {
            btnI01.setBackground(new Color(255, 204, 255));
            btnI02.setBackground(new Color(255, 204, 255));
            i01 = 0;
        }
        else if (i01 == 0) {
            btnI01.setBackground(Color.YELLOW);
            btnI02.setBackground(Color.YELLOW);
            i01 = 1;
        }
    }//GEN-LAST:event_btnI01ActionPerformed

    private void btnI02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnI02ActionPerformed
        if (i01 == 1) {
            btnI01.setBackground(new Color(255, 204, 255));
            btnI02.setBackground(new Color(255, 204, 255));
            i01 = 0;
        }
        else if (i01 == 0) {
            btnI01.setBackground(Color.YELLOW);
            btnI02.setBackground(Color.YELLOW);
            i01 = 1;
        }
    }//GEN-LAST:event_btnI02ActionPerformed

    private void btnI04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnI04ActionPerformed
        if (i04 == 1) {
            btnI04.setBackground(new Color(255, 204, 255));
            btnI05.setBackground(new Color(255, 204, 255));
            i04 = 0;
        }
        else if (i04 == 0) {
            btnI04.setBackground(Color.YELLOW);
            btnI05.setBackground(Color.YELLOW);
            i04 = 1;
        }
    }//GEN-LAST:event_btnI04ActionPerformed

    private void btnI05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnI05ActionPerformed
        if (i04 == 1) {
            btnI04.setBackground(new Color(255, 204, 255));
            btnI05.setBackground(new Color(255, 204, 255));
            i04 = 0;
        }
        else if (i04 == 0) {
            btnI04.setBackground(Color.YELLOW);
            btnI05.setBackground(Color.YELLOW);
            i04 = 1;
        }
    }//GEN-LAST:event_btnI05ActionPerformed

    private void btnI07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnI07ActionPerformed
        if (i07 == 1) {
            btnI07.setBackground(new Color(255, 204, 255));
            btnI08.setBackground(new Color(255, 204, 255));
            i07 = 0;
        }
        else if (i07 == 0) {
            btnI07.setBackground(Color.YELLOW);
            btnI08.setBackground(Color.YELLOW);
            i07 = 1;
        }
    }//GEN-LAST:event_btnI07ActionPerformed

    private void btnI08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnI08ActionPerformed
        if (i07 == 1) {
            btnI07.setBackground(new Color(255, 204, 255));
            btnI08.setBackground(new Color(255, 204, 255));
            i07 = 0;
        }
        else if (i07 == 0) {
            btnI07.setBackground(Color.YELLOW);
            btnI08.setBackground(Color.YELLOW);
            i07 = 1;
        }
    }//GEN-LAST:event_btnI08ActionPerformed

    private void btnI10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnI10ActionPerformed
        if (i10 == 1) {
            btnI10.setBackground(new Color(255, 204, 255));
            btnI11.setBackground(new Color(255, 204, 255));
            i10 = 0;
        }
        else if (i10 == 0) {
            btnI10.setBackground(Color.YELLOW);
            btnI11.setBackground(Color.YELLOW);
            i10 = 1;
        }
    }//GEN-LAST:event_btnI10ActionPerformed

    private void btnI11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnI11ActionPerformed
        if (i10 == 1) {
            btnI10.setBackground(new Color(255, 204, 255));
            btnI11.setBackground(new Color(255, 204, 255));
            i10 = 0;
        }
        else if (i10 == 0) {
            btnI10.setBackground(Color.YELLOW);
            btnI11.setBackground(Color.YELLOW);
            i10 = 1;
        }
    }//GEN-LAST:event_btnI11ActionPerformed

    private void btnJ01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJ01ActionPerformed
        if (j01 == 1) {
            btnJ01.setBackground(Color.LIGHT_GRAY);
            j01 = 0;
        }
        else if (j01 == 0) {
            btnJ01.setBackground(Color.YELLOW);
            j01 = 1;
        }
    }//GEN-LAST:event_btnJ01ActionPerformed

    private void btnJ03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJ03ActionPerformed
        if (j03 == 1) {
            btnJ03.setBackground(Color.LIGHT_GRAY);
            j03 = 0;
        }
        else if (j03 == 0) {
            btnJ03.setBackground(Color.YELLOW);
            j03 = 1;
        }
    }//GEN-LAST:event_btnJ03ActionPerformed

    private void btnJ05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJ05ActionPerformed
        if (j05 == 1) {
            btnJ05.setBackground(Color.LIGHT_GRAY);
            j05 = 0;
        }
        else if (j05 == 0) {
            btnJ05.setBackground(Color.YELLOW);
            j05 = 1;
        }
    }//GEN-LAST:event_btnJ05ActionPerformed

    private void btnJ07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJ07ActionPerformed
        if (j07 == 1) {
            btnJ07.setBackground(Color.LIGHT_GRAY);
            j07 = 0;
        }
        else if (j07 == 0) {
            btnJ07.setBackground(Color.YELLOW);
            j07 = 1;
        }
    }//GEN-LAST:event_btnJ07ActionPerformed

    private void btnJ09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJ09ActionPerformed
        if (j09 == 1) {
            btnJ09.setBackground(Color.LIGHT_GRAY);
            j09 = 0;
        }
        else if (j09 == 0) {
            btnJ09.setBackground(Color.YELLOW);
            j09 = 1;
        }
    }//GEN-LAST:event_btnJ09ActionPerformed

    private void btnJ11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJ11ActionPerformed
        if (j11 == 1) {
            btnJ11.setBackground(Color.LIGHT_GRAY);
            j11 = 0;
        }
        else if (j11 == 0) {
            btnJ11.setBackground(Color.YELLOW);
            j11 = 1;
        }
    }//GEN-LAST:event_btnJ11ActionPerformed

    private void btnK01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnK01ActionPerformed
        if (k01 == 1) {
            btnK01.setBackground(new Color(255, 204, 255));
            btnK02.setBackground(new Color(255, 204, 255));
            k01 = 0;
        }
        else if (k01 == 0) {
            btnK01.setBackground(Color.YELLOW);
            btnK02.setBackground(Color.YELLOW);
            k01 = 1;
        }
    }//GEN-LAST:event_btnK01ActionPerformed

    private void btnK02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnK02ActionPerformed
        if (k01 == 1) {
            btnK01.setBackground(new Color(255, 204, 255));
            btnK02.setBackground(new Color(255, 204, 255));
            k01 = 0;
        }
        else if (k01 == 0) {
            btnK01.setBackground(Color.YELLOW);
            btnK02.setBackground(Color.YELLOW);
            k01 = 1;
        }
    }//GEN-LAST:event_btnK02ActionPerformed

    private void btnK04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnK04ActionPerformed
        if (k04 == 1) {
            btnK04.setBackground(new Color(255, 204, 255));
            btnK05.setBackground(new Color(255, 204, 255));
            k04 = 0;
        }
        else if (k04 == 0) {
            btnK04.setBackground(Color.YELLOW);
            btnK05.setBackground(Color.YELLOW);
            k04 = 1;
        }
    }//GEN-LAST:event_btnK04ActionPerformed

    private void btnK05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnK05ActionPerformed
        if (k04 == 1) {
            btnK04.setBackground(new Color(255, 204, 255));
            btnK05.setBackground(new Color(255, 204, 255));
            k04 = 0;
        }
        else if (k04 == 0) {
            btnK04.setBackground(Color.YELLOW);
            btnK05.setBackground(Color.YELLOW);
            k04 = 1;
        }
    }//GEN-LAST:event_btnK05ActionPerformed

    private void btnK07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnK07ActionPerformed
        if (k07 == 1) {
            btnK07.setBackground(new Color(255, 204, 255));
            btnK08.setBackground(new Color(255, 204, 255));
            k07 = 0;
        }
        else if (k07 == 0) {
            btnK07.setBackground(Color.YELLOW);
            btnK08.setBackground(Color.YELLOW);
            k07 = 1;
        }
    }//GEN-LAST:event_btnK07ActionPerformed

    private void btnK08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnK08ActionPerformed
        if (k07 == 1) {
            btnK07.setBackground(new Color(255, 204, 255));
            btnK08.setBackground(new Color(255, 204, 255));
            k07 = 0;
        }
        else if (k07 == 0) {
            btnK07.setBackground(Color.YELLOW);
            btnK08.setBackground(Color.YELLOW);
            k07 = 1;
        }
    }//GEN-LAST:event_btnK08ActionPerformed

    private void btnK10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnK10ActionPerformed
        if (k10 == 1) {
            btnK10.setBackground(new Color(255, 204, 255));
            btnK11.setBackground(new Color(255, 204, 255));
            k10 = 0;
        }
        else if (k10 == 0) {
            btnK10.setBackground(Color.YELLOW);
            btnK11.setBackground(Color.YELLOW);
            k10 = 1;
        }
    }//GEN-LAST:event_btnK10ActionPerformed

    private void btnK11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnK11ActionPerformed
        if (k10 == 1) {
            btnK10.setBackground(new Color(255, 204, 255));
            btnK11.setBackground(new Color(255, 204, 255));
            k10 = 0;
        }
        else if (k10 == 0) {
            btnK10.setBackground(Color.YELLOW);
            btnK11.setBackground(Color.YELLOW);
            k10 = 1;
        }
    }//GEN-LAST:event_btnK11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seat1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seat1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seat1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seat1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Seat1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnA01;
    private javax.swing.JButton btnA02;
    private javax.swing.JButton btnA04;
    private javax.swing.JButton btnA05;
    private javax.swing.JButton btnA07;
    private javax.swing.JButton btnA08;
    private javax.swing.JButton btnA10;
    private javax.swing.JButton btnA11;
    private javax.swing.JButton btnAvailable;
    private javax.swing.JButton btnB01;
    private javax.swing.JButton btnB03;
    private javax.swing.JButton btnB05;
    private javax.swing.JButton btnB07;
    private javax.swing.JButton btnB09;
    private javax.swing.JButton btnB11;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnC01;
    private javax.swing.JButton btnC02;
    private javax.swing.JButton btnC04;
    private javax.swing.JButton btnC05;
    private javax.swing.JButton btnC07;
    private javax.swing.JButton btnC08;
    private javax.swing.JButton btnC10;
    private javax.swing.JButton btnC11;
    private javax.swing.JButton btnD01;
    private javax.swing.JButton btnD03;
    private javax.swing.JButton btnD05;
    private javax.swing.JButton btnD07;
    private javax.swing.JButton btnD09;
    private javax.swing.JButton btnD11;
    private javax.swing.JButton btnE01;
    private javax.swing.JButton btnE02;
    private javax.swing.JButton btnE04;
    private javax.swing.JButton btnE05;
    private javax.swing.JButton btnE07;
    private javax.swing.JButton btnE08;
    private javax.swing.JButton btnE10;
    private javax.swing.JButton btnE11;
    private javax.swing.JButton btnF01;
    private javax.swing.JButton btnF03;
    private javax.swing.JButton btnF05;
    private javax.swing.JButton btnF07;
    private javax.swing.JButton btnF09;
    private javax.swing.JButton btnF11;
    private javax.swing.JButton btnG01;
    private javax.swing.JButton btnG02;
    private javax.swing.JButton btnG04;
    private javax.swing.JButton btnG05;
    private javax.swing.JButton btnG07;
    private javax.swing.JButton btnG08;
    private javax.swing.JButton btnG10;
    private javax.swing.JButton btnG11;
    private javax.swing.JButton btnH01;
    private javax.swing.JButton btnH03;
    private javax.swing.JButton btnH05;
    private javax.swing.JButton btnH07;
    private javax.swing.JButton btnH09;
    private javax.swing.JButton btnH11;
    private javax.swing.JButton btnI01;
    private javax.swing.JButton btnI02;
    private javax.swing.JButton btnI04;
    private javax.swing.JButton btnI05;
    private javax.swing.JButton btnI07;
    private javax.swing.JButton btnI08;
    private javax.swing.JButton btnI10;
    private javax.swing.JButton btnI11;
    private javax.swing.JButton btnJ01;
    private javax.swing.JButton btnJ03;
    private javax.swing.JButton btnJ05;
    private javax.swing.JButton btnJ07;
    private javax.swing.JButton btnJ09;
    private javax.swing.JButton btnJ11;
    private javax.swing.JButton btnK01;
    private javax.swing.JButton btnK02;
    private javax.swing.JButton btnK04;
    private javax.swing.JButton btnK05;
    private javax.swing.JButton btnK07;
    private javax.swing.JButton btnK08;
    private javax.swing.JButton btnK10;
    private javax.swing.JButton btnK11;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnSelected;
    private javax.swing.JButton btnTwin1;
    private javax.swing.JButton btnTwin2;
    private javax.swing.JButton btnUnavailable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
